package typescript

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/riducms/ridu/schema"
)

// Client generates one application's exact document and SDK binding types.
func Client(manifest schema.Manifest) ([]byte, error) {
	manifestBytes, err := manifest.Bytes()
	if err != nil {
		return nil, fmt.Errorf("encode manifest for generated client registry: %w", err)
	}
	manifestDigest := sha256.Sum256(manifestBytes)

	snapshot := manifest.Snapshot()
	collectionNames := make(map[schema.StableID]string, len(snapshot.Collections)+len(snapshot.Globals))
	usedTypeNames := make(map[string]bool, len(snapshot.Collections)+len(snapshot.Globals))
	pluginTypes := pluginFieldTypes(snapshot.Plugins)
	for _, collection := range snapshot.Collections {
		name := pascal(string(collection.ID))
		collectionNames[collection.ID] = name
		usedTypeNames[name] = true
	}
	for _, global := range snapshot.Globals {
		name := pascal(string(global.Slug))
		if usedTypeNames[name] {
			name = "Global" + name
		}
		collectionNames[global.ID] = name
		usedTypeNames[name] = true
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by Ridu from ridu.schema.json. DO NOT EDIT.\n\n")
	output.WriteString("import { createClient as createRuntimeClient } from \"@riducms/sdk\";\n")
	output.WriteString("import type { ClientOptions, RiduClient } from \"@riducms/sdk\";\n\n")
	output.WriteString("export type ID = string;\n\n")
	if snapshot.Application.Localization != nil {
		locales := make([]string, len(snapshot.Application.Localization.Locales))
		for index, locale := range snapshot.Application.Localization.Locales {
			locales[index] = strconv.Quote(string(locale.Code))
		}
		fmt.Fprintf(&output, "export type Locale = %s;\n\n", strings.Join(locales, " | "))
		output.WriteString("type RiduLocalizedValues<Value> = Partial<Record<Locale, Value>> & {\n")
		output.WriteString("\treadonly [Symbol.toStringTag]?: \"RiduLocalizedValues\";\n")
		output.WriteString("};\n\n")
	}
	output.WriteString("export interface ScalarWhere<Value> {\n")
	output.WriteString("\tequals?: Value;\n\tnotEquals?: Value;\n\tgreaterThan?: Value;\n\tgreaterThanEqual?: Value;\n\tlessThan?: Value;\n\tlessThanEqual?: Value;\n\tcontains?: Value extends string ? string : never;\n\tlike?: Value extends string ? string : never;\n\tin?: readonly Value[];\n\texists?: boolean;\n}\n\n")
	output.WriteString("export type TimestampWhere = Omit<ScalarWhere<string>, \"contains\" | \"like\">;\n\n")
	output.WriteString("export interface MultiSelectWhere<Value extends string> {\n")
	output.WriteString("\tcontains?: Value;\n\texists?: boolean;\n}\n\n")
	output.WriteString("export interface ExistsWhere {\n")
	output.WriteString("\texists?: boolean;\n}\n\n")
	for _, collection := range snapshot.Collections {
		name := collectionNames[collection.ID]
		writeDocumentTypes(&output, name, collection, collectionNames, pluginTypes, snapshot.Application.Localization != nil, snapshot.Application.AllowIDOnCreate)
	}
	for _, global := range snapshot.Globals {
		name := collectionNames[global.ID]
		writeDocumentTypes(&output, name, global, collectionNames, pluginTypes, snapshot.Application.Localization != nil, false)
	}

	output.WriteString("export interface RiduConfig {\n")
	if snapshot.Application.Localization != nil {
		output.WriteString("\tlocale: Locale;\n")
	} else {
		output.WriteString("\tlocale: never;\n")
	}
	output.WriteString("\tcollections: {\n")
	for _, collection := range snapshot.Collections {
		name := collectionNames[collection.ID]
		fmt.Fprintf(&output, "\t\t%s: {\n", property(string(collection.Slug)))
		fmt.Fprintf(&output, "\t\t\tslug: %s;\n", strconv.Quote(string(collection.Slug)))
		fmt.Fprintf(&output, "\t\t\tauth: %t;\n", collection.Capabilities.Auth)
		fmt.Fprintf(&output, "\t\t\tupload: %t;\n", collection.Capabilities.Upload)
		fmt.Fprintf(&output, "\t\t\tversions: %t;\n", collection.Capabilities.Versions)
		fmt.Fprintf(&output, "\t\t\tdrafts: %t;\n", collection.Versions != nil && collection.Versions.Drafts)
		fmt.Fprintf(&output, "\t\t\ttrash: %t;\n", collection.Capabilities.Trash)
		fmt.Fprintf(&output, "\t\t\toutput: %s;\n", name)
		if snapshot.Application.Localization != nil {
			fmt.Fprintf(&output, "\t\t\tallOutput: %sAllLocales;\n", name)
		}
		fmt.Fprintf(&output, "\t\t\tcreate: %sCreate;\n", name)
		fmt.Fprintf(&output, "\t\t\tupdate: %sUpdate;\n", name)
		fmt.Fprintf(&output, "\t\t\twhere: %sWhere;\n", name)
		fmt.Fprintf(&output, "\t\t\tselect: %sSelect;\n", name)
		fmt.Fprintf(&output, "\t\t\tpopulate: %sPopulate;\n", name)
		fmt.Fprintf(&output, "\t\t\tpopulateOutput: %sPopulateOutput;\n", name)
		if snapshot.Application.Localization != nil {
			fmt.Fprintf(&output, "\t\t\tallPopulateOutput: %sAllLocalesPopulateOutput;\n", name)
		}
		fmt.Fprintf(&output, "\t\t\tvalidationPath: %sValidationPath;\n", name)
		output.WriteString("\t\t};\n")
	}
	output.WriteString("\t};\n")
	if len(snapshot.Globals) != 0 {
		output.WriteString("\tglobals: {\n")
		for _, global := range snapshot.Globals {
			name := collectionNames[global.ID]
			fmt.Fprintf(&output, "\t\t%s: {\n", property(string(global.Slug)))
			fmt.Fprintf(&output, "\t\t\tslug: %s;\n", strconv.Quote(string(global.Slug)))
			fmt.Fprintf(&output, "\t\t\tversions: %t;\n", global.Capabilities.Versions)
			fmt.Fprintf(&output, "\t\t\tdrafts: %t;\n", global.Versions != nil && global.Versions.Drafts)
			fmt.Fprintf(&output, "\t\t\toutput: %s;\n", name)
			if snapshot.Application.Localization != nil {
				fmt.Fprintf(&output, "\t\t\tallOutput: %sAllLocales;\n", name)
			}
			fmt.Fprintf(&output, "\t\t\tupdate: %sUpdate;\n", name)
			fmt.Fprintf(&output, "\t\t\tselect: %sSelect;\n", name)
			fmt.Fprintf(&output, "\t\t\tpopulate: %sPopulate;\n", name)
			fmt.Fprintf(&output, "\t\t\tpopulateOutput: %sPopulateOutput;\n", name)
			if snapshot.Application.Localization != nil {
				fmt.Fprintf(&output, "\t\t\tallPopulateOutput: %sAllLocalesPopulateOutput;\n", name)
			}
			fmt.Fprintf(&output, "\t\t\tvalidationPath: %sValidationPath;\n", name)
			output.WriteString("\t\t};\n")
		}
		output.WriteString("\t};\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("declare module \"@riducms/sdk\" {\n")
	output.WriteString("\tinterface GeneratedRiduConfigRegistry {\n")
	fmt.Fprintf(&output, "\t\t%s: RiduConfig;\n", property(fmt.Sprintf("manifest-%x", manifestDigest)))
	output.WriteString("\t}\n}\n\n")
	output.WriteString("export type CollectionSlug = keyof RiduConfig[\"collections\"];\n\n")
	if len(snapshot.Globals) != 0 {
		output.WriteString("export type GlobalSlug = keyof RiduConfig[\"globals\"];\n\n")
	}
	output.WriteString("export function createClient(options: ClientOptions): RiduClient<RiduConfig> {\n")
	output.WriteString("\treturn createRuntimeClient<RiduConfig>(options);\n}\n")
	return output.Bytes(), nil
}

func writeDocumentTypes(output *bytes.Buffer, name string, collection schema.Collection, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, localized, allowIDOnCreate bool) {
	fields := storedFields(collection.Fields)
	inputFields := writableFields(collection.Fields)
	readFields := outputFields(collection.Fields)
	fmt.Fprintf(output, "export interface %s {\n", name)
	output.WriteString("\tid: ID;\n\tcreatedAt: string;\n\tupdatedAt: string;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: string;\n")
	}
	if collection.Versions != nil {
		if collection.Versions.Drafts {
			output.WriteString("\t_status: \"draft\" | \"published\";\n")
		} else {
			output.WriteString("\t_status: \"published\";\n")
		}
		output.WriteString("\t_revision: number;\n")
	}
	if localized {
		output.WriteString("\t_localization?: { sources: Partial<Record<string, Locale>> };\n")
	}
	for _, field := range readFields {
		fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), outputType(field, collectionNames, pluginTypes, 1))
	}
	output.WriteString("}\n\n")
	if localized {
		fmt.Fprintf(output, "export interface %sAllLocales {\n", name)
		output.WriteString("\tid: ID;\n\tcreatedAt: string;\n\tupdatedAt: string;\n")
		if collection.Capabilities.Trash {
			output.WriteString("\tdeletedAt?: string;\n")
		}
		if collection.Versions != nil {
			if collection.Versions.Drafts {
				output.WriteString("\t_status: \"draft\" | \"published\";\n")
			} else {
				output.WriteString("\t_status: \"published\";\n")
			}
			output.WriteString("\t_revision: number;\n")
		}
		for _, field := range readFields {
			fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), allOutputType(field, collectionNames, pluginTypes, 1))
		}
		output.WriteString("}\n\n")
	}

	fmt.Fprintf(output, "export interface %sCreate {\n", name)
	if allowIDOnCreate && !collection.Capabilities.Global {
		output.WriteString("\tid?: ID;\n")
	}
	for _, field := range inputFields {
		optional := !field.Required || typescriptFieldHasDefault(field)
		fmt.Fprintf(output, "\t%s%s: %s;\n", property(field.Name), optionalMark(optional), inputType(field, collectionNames, pluginTypes, 1))
	}
	output.WriteString("}\n\n")

	fmt.Fprintf(output, "export interface %sUpdate {\n", name)
	for _, field := range inputFields {
		fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), inputType(field, collectionNames, pluginTypes, 1))
	}
	output.WriteString("}\n\n")

	fmt.Fprintf(output, "export interface %sWhere {\n", name)
	fmt.Fprintf(output, "\tand?: readonly %sWhere[];\n\tor?: readonly %sWhere[];\n\tnot?: %sWhere;\n", name, name, name)
	output.WriteString("\tid?: ScalarWhere<ID>;\n\tcreatedAt?: TimestampWhere;\n\tupdatedAt?: TimestampWhere;\n")
	if collection.Versions != nil {
		statusType := strconv.Quote("published")
		if collection.Versions.Drafts {
			statusType = strconv.Quote("draft") + " | " + statusType
		}
		fmt.Fprintf(output, "\t_status?: ScalarWhere<%s>;\n", statusType)
	}
	for _, candidate := range whereFields(fields, "") {
		fmt.Fprintf(output, "\t%s?: %s;\n", property(candidate.path), whereType(candidate.field, collectionNames, pluginTypes, 1))
	}
	output.WriteString("}\n\n")

	fmt.Fprintf(output, "export interface %sSelect {\n", name)
	output.WriteString("\tid?: boolean;\n\tcreatedAt?: boolean;\n\tupdatedAt?: boolean;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: boolean;\n")
	}
	if collection.Versions != nil {
		output.WriteString("\t_status?: boolean;\n\t_revision?: boolean;\n")
	}
	// The REST store projection is deliberately top-level: selecting a container
	// includes its complete visible value rather than accepting a nested object.
	for _, field := range readFields {
		fmt.Fprintf(output, "\t%s?: boolean;\n", property(field.Name))
	}
	output.WriteString("}\n\n")

	// Population target projections deliberately exclude join, virtual, and
	// other presentation-only fields. Root REST selects use the broader Select
	// contract above because the operation engine resolves those output fields
	// after the adapter read.
	fmt.Fprintf(output, "export interface %sPopulationSelect {\n", name)
	output.WriteString("\tid?: boolean;\n\tcreatedAt?: boolean;\n\tupdatedAt?: boolean;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: boolean;\n")
	}
	if collection.Versions != nil {
		output.WriteString("\t_status?: boolean;\n\t_revision?: boolean;\n")
	}
	for _, field := range fields {
		fmt.Fprintf(output, "\t%s?: boolean;\n", property(field.Name))
	}
	output.WriteString("}\n\n")

	populateFields := relationshipFields(fields)
	if len(populateFields) == 0 {
		fmt.Fprintf(output, "export type %sPopulate = Record<string, never>;\n\n", name)
		fmt.Fprintf(output, "export type %sPopulateOutput = Record<string, never>;\n\n", name)
		if localized {
			fmt.Fprintf(output, "export type %sAllLocalesPopulateOutput = Record<string, never>;\n\n", name)
		}
	} else {
		fmt.Fprintf(output, "export interface %sPopulate {\n", name)
		for _, field := range populateFields {
			// Population traversal uses canonical schema paths, including array and
			// block containers, because runtime row indexes are not schema paths.
			fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Path.String()), populateType(field, collectionNames))
		}
		output.WriteString("}\n\n")
		fmt.Fprintf(output, "export interface %sPopulateOutput {\n", name)
		for _, field := range populateFields {
			fmt.Fprintf(output, "\t%s: %s;\n", property(field.Path.String()), outputType(field, collectionNames, pluginTypes, 1))
		}
		output.WriteString("}\n\n")
		if localized {
			fmt.Fprintf(output, "export interface %sAllLocalesPopulateOutput {\n", name)
			for _, field := range populateFields {
				fmt.Fprintf(output, "\t%s: %s;\n", property(field.Path.String()), allOutputType(field, collectionNames, pluginTypes, 1))
			}
			output.WriteString("}\n\n")
		}
	}

	paths := validationPaths(inputFields)
	fmt.Fprintf(output, "export type %sValidationPath = ", name)
	if len(paths) == 0 {
		output.WriteString("never;\n\n")
	} else {
		output.WriteString(strings.Join(paths, " | "))
		output.WriteString(";\n\n")
	}
}

func outputType(field schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int) string {
	base := baseType(field, collectionNames, pluginTypes, depth, "output")
	if field.Required || field.Type == schema.FieldTypeJoin {
		return base
	}
	return base + " | null"
}

func inputType(field schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int) string {
	base := baseType(field, collectionNames, pluginTypes, depth, "input")
	if field.Required {
		return base
	}
	return base + " | null"
}

func allOutputType(field schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int) string {
	if field.Localized {
		unlocalized := field
		unlocalized.Localized = false
		valueType := baseType(unlocalized, collectionNames, pluginTypes, depth, "all")
		if !field.Required {
			valueType += " | null"
		}
		return "RiduLocalizedValues<" + valueType + ">"
	}
	base := baseType(field, collectionNames, pluginTypes, depth, "all")
	if field.Required || field.Type == schema.FieldTypeJoin {
		return base
	}
	return base + " | null"
}

func baseType(field schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int, mode string) string {
	switch field.Type {
	case schema.FieldTypeText, schema.FieldTypeCode, schema.FieldTypeTextarea, schema.FieldTypeEmail, schema.FieldTypeDate:
		return "string"
	case schema.FieldTypeNumber:
		return "number"
	case schema.FieldTypeCheckbox:
		return "boolean"
	case schema.FieldTypeJSON:
		return "unknown"
	case schema.FieldTypePoint:
		return "[longitude: number, latitude: number]"
	case schema.FieldTypeVirtual:
		if field.Virtual == nil {
			return "never"
		}
		switch field.Virtual.ValueType {
		case schema.ValueTypeString:
			return "string"
		case schema.ValueTypeNumber:
			return "number"
		case schema.ValueTypeBoolean:
			return "boolean"
		default:
			return "unknown"
		}
	case schema.FieldTypeJoin:
		if field.Join == nil {
			return "never[]"
		}
		return "Array<" + collectionOutputName(collectionNames[field.Join.CollectionID], mode) + ">"
	case schema.FieldTypeSelect, schema.FieldTypeRadio:
		if field.Select == nil || len(field.Select.Choices) == 0 {
			return "never"
		}
		values := make([]string, len(field.Select.Choices))
		for index, choice := range field.Select.Choices {
			values[index] = strconv.Quote(choice.Value)
		}
		choiceType := strings.Join(values, " | ")
		if field.Type == schema.FieldTypeSelect && field.Select.HasMany {
			return "Array<" + choiceType + ">"
		}
		return choiceType
	case schema.FieldTypeRelationship:
		if field.Relationship == nil {
			return "never"
		}
		var relationshipType string
		if field.Relationship.Polymorphic {
			members := make([]string, len(field.Relationship.Targets))
			for index, target := range field.Relationship.Targets {
				value := "ID"
				if mode != "input" {
					value += " | " + collectionOutputName(collectionNames[target.CollectionID], mode)
				}
				members[index] = "{ relationTo: " + strconv.Quote(string(target.CollectionSlug)) + "; id: " + value + " }"
			}
			relationshipType = strings.Join(members, " | ")
		} else if mode != "input" {
			relationshipType = "ID | " + collectionOutputName(collectionNames[field.Relationship.CollectionID], mode)
		} else {
			relationshipType = "ID"
		}
		if field.Relationship.HasMany {
			return "Array<" + relationshipType + ">"
		}
		return relationshipType
	case schema.FieldTypeUpload:
		if field.Upload == nil {
			return "never"
		}
		value := "ID"
		if mode != "input" {
			value += " | " + collectionOutputName(collectionNames[field.Upload.CollectionID], mode)
		}
		if field.Upload.HasMany {
			return "Array<" + value + ">"
		}
		return value
	case schema.FieldTypeGroup:
		if field.Nested == nil {
			return "never"
		}
		return objectType(field.Nested.Fields, collectionNames, pluginTypes, depth, mode, false)
	case schema.FieldTypeArray:
		if field.Nested == nil {
			return "never[]"
		}
		return "Array<" + objectType(field.Nested.Fields, collectionNames, pluginTypes, depth, mode, true) + ">"
	case schema.FieldTypeBlocks:
		if field.Blocks == nil || len(field.Blocks.Types) == 0 {
			return "never[]"
		}
		members := make([]string, len(field.Blocks.Types))
		for index, block := range field.Blocks.Types {
			members[index] = "(" + objectType(block.Fields, collectionNames, pluginTypes, depth, mode, true) + " & { blockType: " + strconv.Quote(block.Key) + " })"
		}
		return "Array<" + strings.Join(members, " | ") + ">"
	case schema.FieldTypePlugin:
		if field.Plugin != nil {
			if mapping, exists := pluginTypes[field.Plugin.Key]; exists {
				name := mapping.TypeScriptOutput
				if mode == "input" {
					name = mapping.TypeScriptInput
				}
				return "import(" + strconv.Quote(mapping.TypeScriptPackage) + ")." + name
			}
		}
		return "unknown"
	default:
		return "never"
	}
}

func collectionOutputName(name, mode string) string {
	if mode == "all" {
		return name + "AllLocales"
	}
	return name
}

func objectType(fields []schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int, mode string, keyed bool) string {
	fields = modeFields(fields, mode)
	var output strings.Builder
	output.WriteString("{\n")
	if keyed {
		fmt.Fprintf(&output, "%s_key?: string;\n", indent(depth+1))
	}
	for _, child := range fields {
		optional := mode != "input" || !child.Required || typescriptFieldHasDefault(child)
		typeName := outputType(child, collectionNames, pluginTypes, depth+1)
		if mode == "input" {
			typeName = inputType(child, collectionNames, pluginTypes, depth+1)
		} else if mode == "all" {
			typeName = allOutputType(child, collectionNames, pluginTypes, depth+1)
		}
		fmt.Fprintf(&output, "%s%s%s: %s;\n", indent(depth+1), property(child.Name), optionalMark(optional), typeName)
	}
	fmt.Fprintf(&output, "%s}", indent(depth))
	return output.String()
}

func typescriptFieldHasDefault(field schema.Field) bool {
	return field.Default != nil ||
		field.Select != nil && field.Select.HasMany && len(field.Select.DefaultValues) != 0 ||
		field.Text != nil && field.Text.Slug != nil
}

func whereType(field schema.Field, collectionNames map[schema.StableID]string, pluginTypes map[string]schema.PluginFieldType, depth int) string {
	if field.Type == schema.FieldTypeGroup || field.Type == schema.FieldTypeArray || field.Type == schema.FieldTypeBlocks {
		return "ExistsWhere"
	}
	if field.Type == schema.FieldTypeRelationship || field.Type == schema.FieldTypeUpload {
		return "ScalarWhere<ID>"
	}
	if field.Type == schema.FieldTypeSelect && field.Select != nil && field.Select.HasMany {
		scalar := field
		selectField := *field.Select
		selectField.HasMany = false
		scalar.Select = &selectField
		return "MultiSelectWhere<" + baseType(scalar, collectionNames, pluginTypes, depth, "output") + ">"
	}
	if field.Type == schema.FieldTypePlugin && field.Plugin != nil {
		if mapping, exists := pluginTypes[field.Plugin.Key]; exists && mapping.TypeScriptWhere != "" {
			return "import(" + strconv.Quote(mapping.TypeScriptPackage) + ")." + mapping.TypeScriptWhere
		}
	}
	return "ScalarWhere<" + baseType(field, collectionNames, pluginTypes, depth, "output") + ">"
}

type whereField struct {
	path  string
	field schema.Field
}

// whereFields mirrors the REST decoder's canonical dotted-path grammar. Group,
// array, and block containers expose their own existence comparison and act as
// traversal nodes; their queryable descendants become separate dotted keys.
func whereFields(fields []schema.Field, prefix string) []whereField {
	var result []whereField
	for _, candidate := range fields {
		if candidate.Category == schema.FieldCategoryPresentation {
			continue
		}
		path := candidate.Path.String()
		if path == "" {
			path = candidate.Name
			if prefix != "" {
				path = prefix + "." + candidate.Name
			}
		}
		switch candidate.Type {
		case schema.FieldTypeGroup, schema.FieldTypeArray:
			result = append(result, whereField{path: path, field: candidate})
			if candidate.Nested != nil {
				result = append(result, whereFields(candidate.Nested.Fields, path)...)
			}
		case schema.FieldTypeBlocks:
			result = append(result, whereField{path: path, field: candidate})
			if candidate.Blocks != nil {
				for _, block := range candidate.Blocks.Types {
					result = append(result, whereFields(block.Fields, path+"."+block.Key)...)
				}
			}
		default:
			result = append(result, whereField{path: path, field: candidate})
		}
	}
	return result
}

func pluginFieldTypes(plugins []schema.Plugin) map[string]schema.PluginFieldType {
	result := make(map[string]schema.PluginFieldType)
	for _, plugin := range plugins {
		for _, fieldType := range plugin.FieldTypes {
			result[fieldType.Key] = fieldType
		}
	}
	return result
}

func storedFields(fields []schema.Field) []schema.Field {
	stored := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		if field.Category != schema.FieldCategoryPresentation {
			stored = append(stored, field)
		}
	}
	return stored
}

func writableFields(fields []schema.Field) []schema.Field {
	writable := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		// Upload metadata is injected by the framework and accepted only through
		// the storage-aware upload operations. An authored upload reference has
		// its Upload descriptor and remains writable.
		if field.Category == schema.FieldCategoryPresentation || field.Category == schema.FieldCategoryUpload && field.Upload == nil {
			continue
		}
		writable = append(writable, field)
	}
	return writable
}

func modeFields(fields []schema.Field, mode string) []schema.Field {
	if mode == "input" {
		return writableFields(fields)
	}
	return storedFields(fields)
}

func validationPaths(fields []schema.Field) []string {
	paths := make([]string, 0, len(fields))
	seen := make(map[string]bool)
	var add func(schema.Field, string)
	appendPath := func(path string, template bool) {
		var value string
		if template {
			value = "`" + path + "`"
		} else {
			value = strconv.Quote(path)
		}
		if !seen[value] {
			seen[value] = true
			paths = append(paths, value)
		}
	}
	add = func(field schema.Field, prefix string) {
		path := field.Name
		if prefix != "" {
			path = prefix + "." + field.Name
		}
		appendPath(path, strings.Contains(path, "${number}"))
		variants := []string{path}
		if field.Localized {
			localizedPath := path + ".${Locale}"
			appendPath(localizedPath, true)
			variants = append(variants, localizedPath)
		}
		for _, variant := range variants {
			switch field.Type {
			case schema.FieldTypeGroup:
				if field.Nested != nil {
					for _, child := range writableFields(field.Nested.Fields) {
						add(child, variant)
					}
				}
			case schema.FieldTypeArray:
				row := variant + ".${number}"
				appendPath(row, true)
				appendPath(row+"._key", true)
				if field.Nested != nil {
					for _, child := range writableFields(field.Nested.Fields) {
						add(child, row)
					}
				}
			case schema.FieldTypeBlocks:
				row := variant + ".${number}"
				appendPath(row, true)
				appendPath(row+"._key", true)
				appendPath(row+".blockType", true)
				if field.Blocks != nil {
					for _, block := range field.Blocks.Types {
						for _, child := range writableFields(block.Fields) {
							add(child, row)
						}
					}
				}
			case schema.FieldTypeSelect:
				if field.Select != nil && field.Select.HasMany {
					appendPath(variant+".${number}", true)
				}
			case schema.FieldTypeRelationship:
				if field.Relationship != nil && field.Relationship.HasMany {
					appendPath(variant+".${number}", true)
				}
			case schema.FieldTypeUpload:
				if field.Upload != nil && field.Upload.HasMany {
					appendPath(variant+".${number}", true)
				}
			}
		}
	}
	for _, field := range fields {
		add(field, "")
	}
	return paths
}

func outputFields(fields []schema.Field) []schema.Field {
	result := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		if field.Category != schema.FieldCategoryPresentation || field.Type == schema.FieldTypeJoin || field.Type == schema.FieldTypeVirtual {
			result = append(result, field)
		}
	}
	return result
}

func populateType(field schema.Field, collectionNames map[schema.StableID]string) string {
	if field.Type == schema.FieldTypeUpload && field.Upload != nil {
		selection := collectionNames[field.Upload.CollectionID] + "PopulationSelect"
		return "boolean | " + selection + " | { depth?: number; select?: " + selection + " }"
	}
	if field.Type == schema.FieldTypeRelationship && field.Relationship != nil {
		var selections []string
		if field.Relationship.Polymorphic {
			for _, target := range field.Relationship.Targets {
				selections = append(selections, collectionNames[target.CollectionID]+"PopulationSelect")
			}
		} else {
			selections = append(selections, collectionNames[field.Relationship.CollectionID]+"PopulationSelect")
		}
		selection := strings.Join(selections, " | ")
		return "boolean | " + selection + " | { depth?: number; select?: " + selection + " }"
	}
	return "never"
}

func relationshipFields(fields []schema.Field) []schema.Field {
	result := make([]schema.Field, 0)
	for _, field := range fields {
		if field.Type == schema.FieldTypeRelationship || field.Type == schema.FieldTypeUpload {
			result = append(result, field)
			continue
		}
		if field.Nested != nil {
			result = append(result, relationshipFields(field.Nested.Fields)...)
		}
		if field.Blocks != nil {
			for _, block := range field.Blocks.Types {
				result = append(result, relationshipFields(block.Fields)...)
			}
		}
	}
	return result
}

func property(value string) string {
	return strconv.Quote(value)
}

func pascal(value string) string {
	parts := strings.FieldsFunc(value, func(character rune) bool {
		return character == '-' || character == '_'
	})
	for index, part := range parts {
		runes := []rune(part)
		if len(runes) != 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func indent(depth int) string {
	return strings.Repeat("\t", depth)
}
