package typescript

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/riducms/ridu/internal/blocktypes"
	"github.com/riducms/ridu/internal/membership"
	"github.com/riducms/ridu/schema"
)

type clientGenerator struct {
	blocks          *blocktypes.Catalog
	draftReadFields map[schema.StableID]bool
	collectionNames map[schema.StableID]string
	pluginTypes     map[string]schema.PluginFieldType
}

// resourcePaths holds one resource's dotted-path contracts.
type resourcePaths struct {
	where      pathDefinition
	populate   pathDefinition
	validation []string
}

// Client generates one application's exact document and SDK binding types.
func Client(manifest schema.Manifest) ([]byte, error) {
	snapshot := manifest.Snapshot()
	// NewManifest also accepts hand-built snapshots, so enforce the loader shape
	// at this generator boundary before dereferencing array elements below.
	if err := schema.ValidateAdminLoaders(snapshot.Application.AdminLoaders); err != nil {
		return nil, err
	}
	catalog, err := blocktypes.Build(snapshot)
	if err != nil {
		return nil, err
	}
	collectionNames := make(map[schema.StableID]string, len(snapshot.Collections)+len(snapshot.Globals))
	usedTypeNames := make(map[string]bool, len(snapshot.Collections)+len(snapshot.Globals))
	for _, collection := range snapshot.Collections {
		name := pascal(string(collection.ID))
		collectionNames[collection.ID] = name
		usedTypeNames[name] = true
	}
	for _, global := range snapshot.Globals {
		name := pascal(string(global.Slug))
		if usedTypeNames[name] {
			name = "Global" + name
		}
		collectionNames[global.ID] = name
		usedTypeNames[name] = true
	}
	generator := &clientGenerator{blocks: catalog, draftReadFields: catalog.DraftReadFields(snapshot), collectionNames: collectionNames, pluginTypes: pluginFieldTypes(snapshot.Plugins)}

	// Resolve every resource's path contracts first: they determine which block
	// variant contracts are emitted ahead of the resources that refer to them.
	contracts := newPathContracts(generator)
	validation := newValidationPaths(contracts)
	paths := make(map[schema.StableID]resourcePaths, len(snapshot.Collections)+len(snapshot.Globals))
	prefixed := false
	for index, resource := range append(append([]schema.Collection{}, snapshot.Collections...), snapshot.Globals...) {
		fields := storedFields(resource.Fields)
		resolved := resourcePaths{populate: contracts.populateDefinition(fields), validation: validation.terms(writableFields(resource.Fields), false)}
		// Globals have no list operation and therefore no filter contract.
		if index < len(snapshot.Collections) {
			resolved.where = contracts.whereDefinition(fields)
		}
		prefixed = prefixed || len(resolved.where.placements) != 0 || len(resolved.populate.placements) != 0
		paths[resource.ID] = resolved
	}
	if contracts.err != nil {
		return nil, contracts.err
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by Ridu from ridu.schema.json. DO NOT EDIT.\n\n")
	output.WriteString("import { createClient as createRuntimeClient } from \"@riducms/sdk\";\n")
	output.WriteString("import type { AuthCollectionSlug, ClientOptions, RiduClient } from \"@riducms/sdk\";\n\n")
	output.WriteString("export type ID = string;\n\n")
	if len(snapshot.Application.AdminLoaders) > 0 {
		output.WriteString("import { createAdminLoader } from \"@riducms/sdk\";\n\n")
		output.WriteString("export interface AdminLoaderInputs {\n")
		for _, loader := range snapshot.Application.AdminLoaders {
			fmt.Fprintf(&output, "\t%q: %s;\n", loader.Key, adminDataType(loader.Input, true))
		}
		output.WriteString("}\n\nexport interface AdminLoaderData {\n")
		for _, loader := range snapshot.Application.AdminLoaders {
			fmt.Fprintf(&output, "\t%q: %s;\n", loader.Key, adminDataType(loader.Output, false))
		}
		output.WriteString("}\n\n")
		output.WriteString("export const adminLoaders = {\n")
		for _, loader := range snapshot.Application.AdminLoaders {
			encoded, err := json.Marshal(loader)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&output, "\t%q: createAdminLoader<AdminLoaderInputs[%q], AdminLoaderData[%q]>(%s),\n", loader.Key, loader.Key, loader.Key, encoded)
		}
		output.WriteString("} as const;\n\n")
	}
	if snapshot.Application.Localization != nil {
		locales := make([]string, len(snapshot.Application.Localization.Locales))
		for index, locale := range snapshot.Application.Localization.Locales {
			locales[index] = strconv.Quote(string(locale.Code))
		}
		fmt.Fprintf(&output, "export type Locale = %s;\n\n", strings.Join(locales, " | "))
		output.WriteString("type RiduLocalizedValues<Value> = Partial<Record<Locale, Value>> & {\n")
		output.WriteString("\treadonly [Symbol.toStringTag]?: \"RiduLocalizedValues\";\n")
		output.WriteString("};\n\n")
	}
	output.WriteString("export interface ScalarWhere<Value> {\n")
	output.WriteString("\tequals?: Value;\n\tnotEquals?: Value;\n\tgreaterThan?: Value;\n\tgreaterThanEqual?: Value;\n\tlessThan?: Value;\n\tlessThanEqual?: Value;\n\tcontains?: Value extends string ? string : never;\n\tlike?: Value extends string ? string : never;\n\tin?: readonly Value[];\n\texists?: boolean;\n}\n\n")
	output.WriteString("export type TimestampWhere = Omit<ScalarWhere<string>, \"contains\" | \"like\">;\n\n")
	// The generated client must not contain the text "any", so this avoids "has-many".
	output.WriteString("/** Item membership for lists, multi-selects, reference lists and polymorphic relationships; wrap `in` in `not` to exclude. */\n")
	output.WriteString("export interface MembershipWhere<Value> {\n")
	output.WriteString("\tin?: readonly Value[];\n\tequals?: null;\n\tnotEquals?: null;\n\texists?: boolean;\n}\n\n")
	output.WriteString("export interface ExistsWhere {\n")
	output.WriteString("\texists?: boolean;\n}\n\n")
	if prefixed {
		output.WriteString("/** Places a nested definition's relative dotted paths under the path prefix of one placement. */\n")
		output.WriteString("export type RiduPrefixedPaths<Prefix extends string, Paths> = {\n")
		output.WriteString("\t[Path in keyof Paths as `${Prefix}${Path & string}`]: Paths[Path];\n};\n\n")
	}
	generator.writeBlockTypes(&output, snapshot.Application.Localization != nil)
	contracts.writeVariantContracts(&output)
	validation.write(&output)
	for _, collection := range snapshot.Collections {
		name := collectionNames[collection.ID]
		generator.writeDocumentTypes(&output, name, collection, paths[collection.ID], snapshot.Application.Localization != nil, snapshot.Application.AllowIDOnCreate)
	}
	for _, global := range snapshot.Globals {
		name := collectionNames[global.ID]
		generator.writeDocumentTypes(&output, name, global, paths[global.ID], snapshot.Application.Localization != nil, false)
	}

	output.WriteString("export interface RiduConfig {\n")
	if snapshot.Application.Localization != nil {
		output.WriteString("\tlocale: Locale;\n")
	} else {
		output.WriteString("\tlocale: never;\n")
	}
	output.WriteString("\tcollections: {\n")
	for _, collection := range snapshot.Collections {
		name := collectionNames[collection.ID]
		fmt.Fprintf(&output, "\t\t%s: {\n", property(string(collection.Slug)))
		fmt.Fprintf(&output, "\t\t\tslug: %s;\n", strconv.Quote(string(collection.Slug)))
		fmt.Fprintf(&output, "\t\t\tauth: %t;\n", collection.Capabilities.Auth)
		fmt.Fprintf(&output, "\t\t\tupload: %t;\n", collection.Capabilities.Upload)
		fmt.Fprintf(&output, "\t\t\tversions: %t;\n", collection.Capabilities.Versions)
		fmt.Fprintf(&output, "\t\t\tdrafts: %t;\n", collection.Versions != nil && collection.Versions.Drafts)
		fmt.Fprintf(&output, "\t\t\ttrash: %t;\n", collection.Capabilities.Trash)
		fmt.Fprintf(&output, "\t\t\toutput: %s;\n", name)
		if snapshot.Application.Localization != nil {
			fmt.Fprintf(&output, "\t\t\tallOutput: %sAllLocales;\n", name)
		}
		fmt.Fprintf(&output, "\t\t\tcreate: %sCreate;\n", name)
		fmt.Fprintf(&output, "\t\t\tupdate: %sUpdate;\n", name)
		if collection.Versions != nil && collection.Versions.Drafts {
			fmt.Fprintf(&output, "\t\t\tdraftCreate: %sDraftCreate;\n\t\t\tdraftUpdate: %sDraftUpdate;\n", name, name)
		}
		fmt.Fprintf(&output, "\t\t\twhere: %sWhere;\n", name)
		fmt.Fprintf(&output, "\t\t\tselect: %sSelect;\n", name)
		fmt.Fprintf(&output, "\t\t\tpopulate: %sPopulate;\n", name)
		fmt.Fprintf(&output, "\t\t\tvalidationPath: %sValidationPath;\n", name)
		output.WriteString("\t\t};\n")
	}
	output.WriteString("\t};\n")
	if len(snapshot.Globals) != 0 {
		output.WriteString("\tglobals: {\n")
		for _, global := range snapshot.Globals {
			name := collectionNames[global.ID]
			fmt.Fprintf(&output, "\t\t%s: {\n", property(string(global.Slug)))
			fmt.Fprintf(&output, "\t\t\tslug: %s;\n", strconv.Quote(string(global.Slug)))
			fmt.Fprintf(&output, "\t\t\tversions: %t;\n", global.Capabilities.Versions)
			fmt.Fprintf(&output, "\t\t\tdrafts: %t;\n", global.Versions != nil && global.Versions.Drafts)
			fmt.Fprintf(&output, "\t\t\toutput: %s;\n", name)
			if snapshot.Application.Localization != nil {
				fmt.Fprintf(&output, "\t\t\tallOutput: %sAllLocales;\n", name)
			}
			fmt.Fprintf(&output, "\t\t\tupdate: %sUpdate;\n", name)
			if global.Versions != nil && global.Versions.Drafts {
				fmt.Fprintf(&output, "\t\t\tdraftUpdate: %sDraftUpdate;\n", name)
			}
			fmt.Fprintf(&output, "\t\t\tselect: %sSelect;\n", name)
			fmt.Fprintf(&output, "\t\t\tpopulate: %sPopulate;\n", name)
			fmt.Fprintf(&output, "\t\t\tvalidationPath: %sValidationPath;\n", name)
			output.WriteString("\t\t};\n")
		}
		output.WriteString("\t};\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("export type CollectionSlug = keyof RiduConfig[\"collections\"];\n\n")
	if len(snapshot.Globals) != 0 {
		output.WriteString("export type GlobalSlug = keyof RiduConfig[\"globals\"];\n\n")
	}
	// DefaultAuth is inferred from options.auth.collection, so a client bound to one auth
	// collection may omit it on auth calls and narrows its sessions to that collection.
	output.WriteString("export function createClient<const DefaultAuth extends AuthCollectionSlug<RiduConfig> = never>(\n")
	output.WriteString("\toptions: ClientOptions<DefaultAuth>\n")
	output.WriteString("): RiduClient<RiduConfig, DefaultAuth> {\n")
	output.WriteString("\treturn createRuntimeClient<RiduConfig, DefaultAuth>(options);\n}\n")
	return output.Bytes(), nil
}

func adminDataType(value schema.AdminDataType, input bool) string {
	result := value.Kind
	switch value.Kind {
	case "object":
		var fields []string
		for name, field := range value.Fields {
			optional := ""
			if field.Optional || input {
				optional = "?"
			}
			fields = append(fields, strconv.Quote(name)+optional+": "+adminDataType(field, input))
		}
		sort.Strings(fields)
		result = "{ " + strings.Join(fields, "; ") + " }"
	case "array":
		result = "Array<" + adminDataType(*value.Element, input) + ">"
	}
	if value.Nullable {
		result += " | null"
	}
	return result
}

func (generator *clientGenerator) writeDocumentTypes(output *bytes.Buffer, name string, collection schema.Collection, paths resourcePaths, localized, allowIDOnCreate bool) {
	fields := storedFields(collection.Fields)
	inputFields := writableFields(collection.Fields)
	readFields := outputFields(collection.Fields)
	fmt.Fprintf(output, "export interface %s {\n", name)
	output.WriteString("\tid: ID;\n\tcreatedAt: string;\n\tupdatedAt: string;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: string;\n")
	}
	if collection.Versions != nil {
		if collection.Versions.Drafts {
			output.WriteString("\t_status: \"draft\" | \"published\";\n")
			output.WriteString("\t_publishedRevision?: number;\n\t_hasDraftChanges?: boolean;\n")
		} else {
			output.WriteString("\t_status: \"published\";\n")
		}
	}
	if collection.Versions != nil || collection.Upload != nil {
		output.WriteString("\t_revision: number;\n")
	}
	if localized {
		output.WriteString("\t_localization?: { sources: Partial<Record<string, Locale>> };\n")
	}
	for _, field := range readFields {
		fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), generator.outputType(field, 1))
	}
	output.WriteString("}\n\n")
	if localized {
		fmt.Fprintf(output, "export interface %sAllLocales {\n", name)
		output.WriteString("\tid: ID;\n\tcreatedAt: string;\n\tupdatedAt: string;\n")
		if collection.Capabilities.Trash {
			output.WriteString("\tdeletedAt?: string;\n")
		}
		if collection.Versions != nil {
			if collection.Versions.Drafts {
				output.WriteString("\t_status: \"draft\" | \"published\";\n")
				output.WriteString("\t_publishedRevision?: number;\n\t_hasDraftChanges?: boolean;\n")
			} else {
				output.WriteString("\t_status: \"published\";\n")
			}
		}
		if collection.Versions != nil || collection.Upload != nil {
			output.WriteString("\t_revision: number;\n")
		}
		for _, field := range readFields {
			fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), generator.allOutputType(field, 1))
		}
		output.WriteString("}\n\n")
	}

	fmt.Fprintf(output, "export interface %sCreate {\n", name)
	if allowIDOnCreate && !collection.Capabilities.Global {
		output.WriteString("\tid?: ID;\n")
	}
	for _, field := range inputFields {
		optional := !typescriptInputRequired(field) || typescriptFieldHasDefault(field)
		fmt.Fprintf(output, "\t%s%s: %s;\n", property(field.Name), optionalMark(optional), generator.inputType(field, 1))
	}
	output.WriteString("}\n\n")

	fmt.Fprintf(output, "export interface %sUpdate {\n", name)
	for _, field := range inputFields {
		fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), generator.updateType(field, 1))
	}
	output.WriteString("}\n\n")

	if collection.Versions != nil && collection.Versions.Drafts {
		for _, mode := range []string{"draft", "draftUpdate"} {
			suffix := "DraftCreate"
			if mode == "draftUpdate" {
				suffix = "DraftUpdate"
			}
			fmt.Fprintf(output, "export interface %s%s {\n", name, suffix)
			if mode == "draft" && allowIDOnCreate {
				output.WriteString("\tid?: ID;\n")
			}
			for _, field := range inputFields {
				if collection.Auth != nil && field.Name == collection.Auth.IdentityField {
					fmt.Fprintf(output, "\t%s%s: %s;\n", property(field.Name), optionalMark(mode == "draftUpdate"), generator.inputType(field, 1))
				} else {
					fmt.Fprintf(output, "\t%s?: %s;\n", property(field.Name), generator.draftInputType(field, 1, mode))
				}
			}
			output.WriteString("}\n\n")
		}
	}

	if !collection.Capabilities.Global {
		// Nested block filters are inherited from each variant's relative contract.
		members := []string{
			"and?: readonly " + name + "Where[];", "or?: readonly " + name + "Where[];", "not?: " + name + "Where;",
			"id?: ScalarWhere<ID>;", "createdAt?: TimestampWhere;", "updatedAt?: TimestampWhere;",
		}
		if collection.Versions != nil {
			statusType := strconv.Quote("published")
			if collection.Versions.Drafts {
				statusType = strconv.Quote("draft") + " | " + statusType
			}
			members = append(members, "_status?: ScalarWhere<"+statusType+">;")
		}
		writePathInterface(output, name+"Where", paths.where.placements, "Where", append(members, generator.whereMembers(paths.where)...))
	}

	fmt.Fprintf(output, "export interface %sSelect {\n", name)
	output.WriteString("\tid?: boolean;\n\tcreatedAt?: boolean;\n\tupdatedAt?: boolean;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: boolean;\n")
	}
	if collection.Versions != nil {
		output.WriteString("\t_status?: boolean;\n")
	}
	if collection.Versions != nil || collection.Upload != nil {
		output.WriteString("\t_revision?: boolean;\n")
	}
	// The REST store projection is deliberately top-level: selecting a container
	// includes its complete visible value rather than accepting a nested object.
	for _, field := range readFields {
		fmt.Fprintf(output, "\t%s?: boolean;\n", property(field.Name))
	}
	output.WriteString("}\n\n")

	// Population target projections deliberately exclude join, virtual, and
	// other presentation-only fields. Root REST selects use the broader Select
	// contract above because the operation engine resolves those output fields
	// after the adapter read.
	fmt.Fprintf(output, "export interface %sPopulationSelect {\n", name)
	output.WriteString("\tid?: boolean;\n\tcreatedAt?: boolean;\n\tupdatedAt?: boolean;\n")
	if collection.Capabilities.Trash {
		output.WriteString("\tdeletedAt?: boolean;\n")
	}
	if collection.Versions != nil {
		output.WriteString("\t_status?: boolean;\n")
	}
	if collection.Versions != nil || collection.Upload != nil {
		output.WriteString("\t_revision?: boolean;\n")
	}
	for _, field := range fields {
		fmt.Fprintf(output, "\t%s?: boolean;\n", property(field.Name))
	}
	output.WriteString("}\n\n")

	// Population traversal uses canonical schema paths, including array and
	// block containers, because runtime row indexes are not schema paths.
	if len(paths.populate.entries) == 0 && len(paths.populate.placements) == 0 {
		fmt.Fprintf(output, "export type %sPopulate = Record<string, never>;\n\n", name)
	} else {
		writePathInterface(output, name+"Populate", paths.populate.placements, "Populate", generator.populateMembers(paths.populate))
	}

	fmt.Fprintf(output, "export type %sValidationPath = ", name)
	if len(paths.validation) == 0 {
		output.WriteString("never;\n\n")
	} else {
		output.WriteString(strings.Join(paths.validation, " | "))
		output.WriteString(";\n\n")
	}
}

func (generator *clientGenerator) outputType(field schema.Field, depth int) string {
	base := generator.baseType(field, depth, "output")
	if field.Required && !generator.draftReadFields[field.ID] || field.Type == schema.FieldTypeJoin {
		return base
	}
	return base + " | null"
}

func (generator *clientGenerator) inputType(field schema.Field, depth int) string {
	base := generator.baseType(field, depth, "input")
	if typescriptInputRequired(field) {
		return base
	}
	return base + " | null"
}

func (generator *clientGenerator) updateType(field schema.Field, depth int) string {
	base := generator.baseType(field, depth, "update")
	if !typescriptInputRequired(field) {
		base += " | null"
	}
	return base
}

// Draft inputs defer editorial completeness, not codec or row identity. Walk
// the declared field graph instead of weakening every property with DeepPartial.
func (generator *clientGenerator) draftInputType(field schema.Field, depth int, mode string) string {
	return generator.baseType(field, depth, mode) + " | null"
}

func typescriptWriteMode(mode string) bool {
	return mode == "input" || mode == "update" || mode == "draft" || mode == "draftUpdate"
}

func (generator *clientGenerator) allOutputType(field schema.Field, depth int) string {
	if field.Localized {
		unlocalized := field
		unlocalized.Localized = false
		valueType := generator.baseType(unlocalized, depth, "allValue")
		if !field.Required || generator.draftReadFields[field.ID] {
			valueType += " | null"
		}
		return "RiduLocalizedValues<" + valueType + ">"
	}
	base := generator.baseType(field, depth, "all")
	if field.Required && !generator.draftReadFields[field.ID] || field.Type == schema.FieldTypeJoin {
		return base
	}
	return base + " | null"
}

func (generator *clientGenerator) baseType(field schema.Field, depth int, mode string) string {
	switch field.Type {
	case schema.FieldTypeText, schema.FieldTypeCode, schema.FieldTypeTextarea, schema.FieldTypeEmail, schema.FieldTypeDate:
		return "string"
	case schema.FieldTypeNumber:
		return "number"
	case schema.FieldTypeTextList:
		return "string[]"
	case schema.FieldTypeNumberList:
		return "number[]"
	case schema.FieldTypeCheckbox:
		return "boolean"
	case schema.FieldTypeJSON:
		return "unknown"
	case schema.FieldTypePoint:
		return "[longitude: number, latitude: number]"
	case schema.FieldTypeVirtual:
		if field.Virtual == nil {
			return "never"
		}
		switch field.Virtual.ValueType {
		case schema.ValueTypeString:
			return "string"
		case schema.ValueTypeNumber:
			return "number"
		case schema.ValueTypeBoolean:
			return "boolean"
		default:
			return "unknown"
		}
	case schema.FieldTypeJoin:
		if field.Join == nil {
			return "never[]"
		}
		return "Array<" + collectionOutputName(generator.collectionNames[field.Join.CollectionID], mode) + ">"
	case schema.FieldTypeSelect, schema.FieldTypeRadio:
		if field.Select == nil || len(field.Select.Options) == 0 {
			return "never"
		}
		values := make([]string, len(field.Select.Options))
		for index, option := range field.Select.Options {
			values[index] = strconv.Quote(option.Value)
		}
		optionType := strings.Join(values, " | ")
		if field.Type == schema.FieldTypeSelect && field.Select.HasMany {
			return "Array<" + optionType + ">"
		}
		return optionType
	case schema.FieldTypeRelationship:
		if field.Relationship == nil {
			return "never"
		}
		var relationshipType string
		if field.Relationship.Polymorphic {
			members := make([]string, len(field.Relationship.Targets))
			for index, target := range field.Relationship.Targets {
				value := "ID"
				if !typescriptWriteMode(mode) {
					value += " | " + collectionOutputName(generator.collectionNames[target.CollectionID], mode)
				}
				members[index] = "{ relationTo: " + strconv.Quote(string(target.CollectionSlug)) + "; id: " + value + " }"
			}
			relationshipType = strings.Join(members, " | ")
		} else if !typescriptWriteMode(mode) {
			relationshipType = "ID | " + collectionOutputName(generator.collectionNames[field.Relationship.CollectionID], mode)
		} else {
			relationshipType = "ID"
		}
		if field.Relationship.HasMany {
			return "Array<" + relationshipType + ">"
		}
		return relationshipType
	case schema.FieldTypeUpload:
		if field.Upload == nil {
			return "never"
		}
		value := "ID"
		if !typescriptWriteMode(mode) {
			value += " | " + collectionOutputName(generator.collectionNames[field.Upload.CollectionID], mode)
		}
		if field.Upload.HasMany {
			return "Array<" + value + ">"
		}
		return value
	case schema.FieldTypeGroup:
		if field.Nested == nil {
			return "never"
		}
		return generator.objectType(field.Nested.ResolvedFields(), depth, mode, false)
	case schema.FieldTypeArray:
		if field.Nested == nil {
			return "never[]"
		}
		if mode == "update" {
			return "Array<" + generator.objectType(field.Nested.ResolvedFields(), depth, "input", true) + " | " + generator.objectType(field.Nested.ResolvedFields(), depth, "update", true) + ">"
		}
		if mode == "draftUpdate" {
			return "Array<" + generator.objectType(field.Nested.ResolvedFields(), depth, "draft", true) + " | " + generator.objectType(field.Nested.ResolvedFields(), depth, mode, true) + ">"
		}
		return "Array<" + generator.objectType(field.Nested.ResolvedFields(), depth, mode, true) + ">"
	case schema.FieldTypeBlocks:
		if field.Blocks == nil || len(field.Blocks.BlockReferences) == 0 {
			return "never[]"
		}
		definition := generator.blocks.Fields[field.ID]
		name := definition.Name
		if mode == "input" {
			name += "Input"
		} else if mode == "update" {
			name += "Update"
		} else if mode == "draft" {
			name += "DraftInput"
		} else if mode == "draftUpdate" {
			name += "DraftUpdate"
		} else if mode == "all" {
			name += "AllLocales"
		} else if mode == "allValue" {
			name += "AllLocalesValue"
		}
		return name
	case schema.FieldTypePlugin:
		if field.Plugin != nil {
			if mapping, exists := generator.pluginTypes[field.Plugin.Key]; exists {
				name := mapping.TypeScriptOutput
				if typescriptWriteMode(mode) {
					name = mapping.TypeScriptInput
				}
				result := "import(" + strconv.Quote(mapping.TypeScriptPackage) + ")." + name
				if len(mapping.EmbeddedTypes) > 0 {
					var args []string
					for _, payload := range schema.EmbeddedTypeFields(field, mapping.EmbeddedTypes) {
						container := generator.baseType(payload, depth, mode)
						args = append(args, container+"[number]")
					}
					result += "<" + strings.Join(args, ", ") + ">"
				}
				return result
			}
		}
		return "unknown"
	default:
		return "never"
	}
}

func collectionOutputName(name, mode string) string {
	if mode == "all" || mode == "allValue" {
		return name + "AllLocales"
	}
	return name
}

func (generator *clientGenerator) objectType(fields []schema.Field, depth int, mode string, keyed bool) string {
	fields = modeFields(fields, mode)
	var output strings.Builder
	output.WriteString("{\n")
	if keyed {
		fmt.Fprintf(&output, "%s_key%s: string;\n", indent(depth+1), optionalMark(mode == "input" || mode == "draft"))
	}
	for _, child := range fields {
		optional := mode != "input" || !typescriptInputRequired(child) || typescriptFieldHasDefault(child)
		typeName := generator.outputType(child, depth+1)
		if mode == "input" {
			typeName = generator.inputType(child, depth+1)
		} else if mode == "update" {
			typeName = generator.updateType(child, depth+1)
		} else if mode == "draft" || mode == "draftUpdate" {
			typeName = generator.draftInputType(child, depth+1, mode)
		} else if mode == "all" {
			typeName = generator.allOutputType(child, depth+1)
		} else if mode == "allValue" {
			typeName = generator.baseType(child, depth+1, mode)
			if (!child.Required || generator.draftReadFields[child.ID]) && child.Type != schema.FieldTypeJoin {
				typeName += " | null"
			}
		}
		fmt.Fprintf(&output, "%s%s%s: %s;\n", indent(depth+1), property(child.Name), optionalMark(optional), typeName)
	}
	fmt.Fprintf(&output, "%s}", indent(depth))
	return output.String()
}

func typescriptFieldHasDefault(field schema.Field) bool {
	return field.Default != nil || field.DynamicDefault ||
		field.Select != nil && field.Select.HasMany && len(field.Select.DefaultValues) != 0 ||
		field.Text != nil && field.Text.Slug != nil
}

func (generator *clientGenerator) whereType(field schema.Field) string {
	if field.Type == schema.FieldTypeGroup || field.Type == schema.FieldTypeArray || field.Type == schema.FieldTypeBlocks {
		return "ExistsWhere"
	}
	switch membership.KindOf(field) {
	case membership.Numbers:
		return "MembershipWhere<number>"
	case membership.References:
		// A candidate has the relationship's write shape: { relationTo, id }.
		single := field
		relationship := *field.Relationship
		relationship.HasMany = false
		single.Relationship = &relationship
		return "MembershipWhere<" + generator.baseType(single, 1, "input") + ">"
	case membership.Strings:
		switch field.Type {
		case schema.FieldTypeSelect:
			single := field
			selectField := *field.Select
			selectField.HasMany = false
			single.Select = &selectField
			return "MembershipWhere<" + generator.baseType(single, 1, "output") + ">"
		case schema.FieldTypeTextList:
			return "MembershipWhere<string>"
		default:
			return "MembershipWhere<ID>"
		}
	}
	if field.Type == schema.FieldTypeRelationship || field.Type == schema.FieldTypeUpload {
		return "ScalarWhere<ID>"
	}
	if field.Type == schema.FieldTypePlugin && field.Plugin != nil {
		if mapping, exists := generator.pluginTypes[field.Plugin.Key]; exists && mapping.TypeScriptWhere != "" {
			return "import(" + strconv.Quote(mapping.TypeScriptPackage) + ")." + mapping.TypeScriptWhere
		}
	}
	return "ScalarWhere<" + generator.baseType(field, 1, "output") + ">"
}

func pluginFieldTypes(plugins []schema.Plugin) map[string]schema.PluginFieldType {
	result := make(map[string]schema.PluginFieldType)
	for _, plugin := range plugins {
		for _, fieldType := range plugin.FieldTypes {
			result[fieldType.Key] = fieldType
		}
	}
	return result
}

func storedFields(fields []schema.Field) []schema.Field {
	stored := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		if field.Category != schema.FieldCategoryPresentation {
			stored = append(stored, field)
		}
	}
	return stored
}

func writableFields(fields []schema.Field) []schema.Field {
	writable := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		// Upload metadata is injected by the framework and accepted only through
		// the storage-aware upload operations. An authored upload reference has
		// its Upload descriptor and remains writable.
		if field.Category == schema.FieldCategoryPresentation || field.Category == schema.FieldCategoryUpload && field.Upload == nil {
			continue
		}
		writable = append(writable, field)
	}
	return writable
}

func modeFields(fields []schema.Field, mode string) []schema.Field {
	if typescriptWriteMode(mode) {
		return writableFields(fields)
	}
	return storedFields(fields)
}

func outputFields(fields []schema.Field) []schema.Field {
	result := make([]schema.Field, 0, len(fields))
	for _, field := range fields {
		if field.Category != schema.FieldCategoryPresentation || field.Type == schema.FieldTypeJoin || field.Type == schema.FieldTypeVirtual {
			result = append(result, field)
		}
	}
	return result
}

func (generator *clientGenerator) populateType(field schema.Field) string {
	if field.Type == schema.FieldTypeUpload && field.Upload != nil {
		selection := generator.collectionNames[field.Upload.CollectionID] + "PopulationSelect"
		return "boolean | " + selection + " | { depth?: number; select?: " + selection + " }"
	}
	if field.Type == schema.FieldTypeRelationship && field.Relationship != nil {
		var selections []string
		if field.Relationship.Polymorphic {
			for _, target := range field.Relationship.Targets {
				selections = append(selections, generator.collectionNames[target.CollectionID]+"PopulationSelect")
			}
		} else {
			selections = append(selections, generator.collectionNames[field.Relationship.CollectionID]+"PopulationSelect")
		}
		selection := strings.Join(selections, " | ")
		return "boolean | " + selection + " | { depth?: number; select?: " + selection + " }"
	}
	return "never"
}

// compactProperty preserves ordinary discriminator formatting while quoting
// literal envelope keys that are not TypeScript identifiers.
func compactProperty(value string) string {
	if value == "" {
		return property(value)
	}
	for index, char := range value {
		if !(char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char == '_' || char == '$' || index > 0 && char >= '0' && char <= '9') {
			return property(value)
		}
	}
	return value
}

func property(value string) string {
	return strconv.Quote(value)
}

func pascal(value string) string {
	parts := strings.FieldsFunc(value, func(character rune) bool {
		return character == '-' || character == '_'
	})
	for index, part := range parts {
		runes := []rune(part)
		if len(runes) != 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func indent(depth int) string {
	return strings.Repeat("\t", depth)
}

// Named variants are generated from the same resolved definitions used by Go and OpenAPI.
func (generator *clientGenerator) writeBlockTypes(output *bytes.Buffer, localized bool) {
	modes := []string{"input", "update", "output"}
	if len(generator.draftReadFields) > 0 {
		modes = append(modes, "draft", "draftUpdate")
	}
	if localized {
		modes = append(modes, "all", "allValue")
	}
	for _, variant := range generator.blocks.Variants {
		for _, mode := range modes {
			name := variant.Name
			if mode == "input" {
				name = variant.Name + "Input"
			} else if mode == "update" {
				name = variant.Name + "Update"
			} else if mode == "draft" {
				name = variant.Name + "DraftInput"
			} else if mode == "draftUpdate" {
				name = variant.Name + "DraftUpdate"
			} else if mode == "all" {
				name = variant.Name + "AllLocales"
			} else if mode == "allValue" {
				name = variant.Name + "AllLocalesValue"
			}
			if mode == "update" {
				output.WriteString("/** Patch a retained row by _key. New identities must satisfy the input contract at runtime. */\n")
			}
			body := generator.objectType(variant.Block.ResolvedFields(), 0, mode, false)
			fmt.Fprintf(output, "export type %s = %s & { %s: %s; %s%s: string };\n\n", name, body, compactProperty(variant.Discriminator), strconv.Quote(variant.Block.Slug), compactProperty(variant.Identity), optionalMark(mode == "input" || mode == "draft"))
		}
	}
	fieldNames := make([]string, 0, len(generator.blocks.Fields))
	fields := make(map[string]blocktypes.Field)
	for _, definition := range generator.blocks.Fields {
		if _, exists := fields[definition.Name]; !exists {
			fieldNames = append(fieldNames, definition.Name)
			fields[definition.Name] = definition
		}
	}
	sort.Strings(fieldNames)
	for _, name := range fieldNames {
		definition := fields[name]
		for _, mode := range modes {
			suffix, variantSuffix := "", ""
			if mode == "input" {
				suffix, variantSuffix = "Input", "Input"
			} else if mode == "update" {
				suffix, variantSuffix = "Update", "Update"
			} else if mode == "draft" {
				suffix, variantSuffix = "DraftInput", "DraftInput"
			} else if mode == "draftUpdate" {
				suffix, variantSuffix = "DraftUpdate", "DraftUpdate"
			} else if mode == "all" {
				suffix, variantSuffix = "AllLocales", "AllLocales"
			} else if mode == "allValue" {
				suffix, variantSuffix = "AllLocalesValue", "AllLocalesValue"
			}
			members := make([]string, len(definition.Variants))
			for index, variant := range definition.Variants {
				members[index] = variant + variantSuffix
				if mode == "update" {
					members[index] += " | " + variant + "Input"
				} else if mode == "draftUpdate" {
					members[index] += " | " + variant + "DraftInput"
				}
			}
			union := strings.Join(members, " | ")
			if len(members) == 0 {
				union = "never"
			}
			fmt.Fprintf(output, "export type %sBlock%s = %s;\n", name, suffix, union)
			fmt.Fprintf(output, "export type %s%s = Array<%sBlock%s>;\n\n", name, suffix, name, suffix)
		}
	}
}

func typescriptInputRequired(field schema.Field) bool {
	return field.Required || ((field.Type == schema.FieldTypeTextList || field.Type == schema.FieldTypeNumberList) && field.List != nil && field.List.MinRows > 0)
}
