// Package typescript generates checked TypeScript contracts from Go-owned
// protocol and schema constants.
package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/riducms/ridu/protocol"
	"github.com/riducms/ridu/schema"
)

// Protocol generates the framework-level TypeScript wire contract.
func Protocol() []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by Ridu from Go protocol contracts. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const PROTOCOL_VERSION = %d as const;\n\n", protocol.CurrentVersion)
	fmt.Fprintf(&output, "export const ADMIN_PREPARED_ROUTE_STATE_VERSION = %d as const;\n\n", protocol.AdminPreparedRouteStateVersion)
	fmt.Fprintf(&output, "export const ADMIN_PREPARED_ROUTE_STATE_MEDIA_TYPE = %q as const;\n\n", protocol.AdminPreparedRouteStateMediaType)
	writeUnion(&output, "AdminPreparedRouteOutcomeV1", []string{
		string(protocol.AdminPreparedRoutePrepared),
		string(protocol.AdminPreparedRouteRedirect),
		string(protocol.AdminPreparedRouteReload),
		string(protocol.AdminPreparedRouteFallback),
	})
	adminRouteKinds := []string{
		string(protocol.AdminPreparedRouteLogin),
		string(protocol.AdminPreparedRouteSetup),
		string(protocol.AdminPreparedRouteDashboard),
		string(protocol.AdminPreparedRouteCustom),
		string(protocol.AdminPreparedRouteCollectionList),
		string(protocol.AdminPreparedRouteCollectionTrash),
		string(protocol.AdminPreparedRouteCollectionCreate),
		string(protocol.AdminPreparedRouteCollectionDocument),
		string(protocol.AdminPreparedRouteCollectionAPI),
		string(protocol.AdminPreparedRouteCollectionVersions),
		string(protocol.AdminPreparedRouteGlobalVersions),
		string(protocol.AdminPreparedRouteUpload),
		string(protocol.AdminPreparedRouteGlobalDocument),
		string(protocol.AdminPreparedRouteGlobalAPI),
		string(protocol.AdminPreparedRouteAccount),
		string(protocol.AdminPreparedRouteSecurity),
		string(protocol.AdminPreparedRouteNotFound),
		string(protocol.AdminPreparedRouteError),
	}
	writeUnion(&output, "AdminPreparedRouteKindV1", adminRouteKinds)
	writeUnion(&output, "ErrorCode", []string{
		string(protocol.ErrorValidation),
		string(protocol.ErrorAccess),
		string(protocol.ErrorNotFound),
		string(protocol.ErrorConflict),
		string(protocol.ErrorDeleteRestricted),
		string(protocol.ErrorBadRequest),
		string(protocol.ErrorInternal),
		string(protocol.ErrorRateLimited),
		string(protocol.ErrorEmailNotVerified),
		string(protocol.ErrorAuthFeatureDisabled),
		string(protocol.ErrorInvalidAuthToken),
		string(protocol.ErrorInvalidCredential),
		string(protocol.ErrorInvalidPreviewToken),
		string(protocol.ErrorRejected),
		string(protocol.ErrorSelectionTooLarge),
	})
	writeUnion(&output, "FieldType", []string{
		string(schema.FieldTypeText),
		string(schema.FieldTypeTextList),
		string(schema.FieldTypeCode),
		string(schema.FieldTypeSelect),
		string(schema.FieldTypeRadio),
		string(schema.FieldTypePoint),
		string(schema.FieldTypeUI),
		string(schema.FieldTypeJoin),
		string(schema.FieldTypeVirtual),
		string(schema.FieldTypeRelationship),
		string(schema.FieldTypeUpload),
		string(schema.FieldTypeGroup),
		string(schema.FieldTypeTextarea),
		string(schema.FieldTypeEmail),
		string(schema.FieldTypeDate),
		string(schema.FieldTypeNumber),
		string(schema.FieldTypeNumberList),
		string(schema.FieldTypeCheckbox),
		string(schema.FieldTypeJSON),
		string(schema.FieldTypeArray),
		string(schema.FieldTypeBlocks),
		string(schema.FieldTypePlugin),
	})
	writeUnion(&output, "FieldCategory", []string{
		string(schema.FieldCategoryScalar),
		string(schema.FieldCategoryNested),
		string(schema.FieldCategoryPresentation),
		string(schema.FieldCategoryRelationship),
		string(schema.FieldCategoryUpload),
		string(schema.FieldCategoryPlugin),
	})
	fmt.Fprintf(&output, "export const SCHEMA_MANIFEST_VERSION = %d as const;\n\n", schema.CurrentVersion)
	fmt.Fprintf(&output, "export const ADMIN_PLUGIN_API_VERSION = %d as const;\n\n", schema.CurrentAdminPluginAPIVersion)
	output.WriteString("export type AdminPreparedRouteDataV1 =\n")
	for index, kind := range adminRouteKinds {
		terminator := ""
		if index == len(adminRouteKinds)-1 {
			terminator = ";"
		}
		fields := ""
		switch protocol.AdminPreparedRouteKindV1(kind) {
		case protocol.AdminPreparedRouteCollectionList, protocol.AdminPreparedRouteCollectionTrash:
			fields = "; data: AdminCollectionListDataV1"
		case protocol.AdminPreparedRouteCollectionCreate:
			fields = "; create: AdminCreateDataV1"
		case protocol.AdminPreparedRouteCollectionDocument, protocol.AdminPreparedRouteGlobalDocument, protocol.AdminPreparedRouteAccount:
			fields = "; document: AdminDocumentDataV1"
		case protocol.AdminPreparedRouteCollectionAPI, protocol.AdminPreparedRouteGlobalAPI:
			fields = "; document: AdminDocumentDataV1"
		case protocol.AdminPreparedRouteCollectionVersions, protocol.AdminPreparedRouteGlobalVersions:
			fields = "; versions: AdminVersionsDataV1"
		case protocol.AdminPreparedRouteUpload:
			fields = "; access: AdminReadResultV1<AccessCapabilitiesEnvelope>"
		case protocol.AdminPreparedRouteSecurity:
			fields = "; security: AdminSecurityDataV1"
		}
		fmt.Fprintf(&output, "\t| { kind: %q%s }%s\n", kind, fields, terminator)
	}
	output.WriteByte('\n')
	output.WriteString(protocolInterfaces)
	return output.Bytes()
}

// AdminBootstrapProtocol generates the build-owned copy of the admin route
// state version without making the build package depend on a runtime package.
func AdminBootstrapProtocol() []byte {
	return []byte(fmt.Sprintf(
		"// Code generated by Ridu from Go protocol contracts. DO NOT EDIT.\n\nexport const ADMIN_PREPARED_ROUTE_STATE_VERSION = %d as const;\n",
		protocol.AdminPreparedRouteStateVersion,
	))
}

func writeUnion(output *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(output, "export type %s =\n", name)
	for index, value := range values {
		terminator := ""
		if index == len(values)-1 {
			terminator = ";"
		}
		fmt.Fprintf(output, "\t| %q%s\n", value, terminator)
	}
	output.WriteByte('\n')
}

var protocolInterfaces = strings.TrimSpace(`
/** Crop and focal coordinates are percentages of the oriented source image. */
export interface UploadGrantRequestItem {
	id: string;
	size?: string;
}

export interface UploadGrantsRequest {
	items: UploadGrantRequestItem[];
	expiresIn?: number;
}

export interface UploadGrant {
	id: string;
	size?: string;
	url: string;
	expiresAt: string;
}

export interface UploadGrantsEnvelope {
	grants: UploadGrant[];
}

export interface UploadImageEdit {
  focalX: number;
  focalY: number;
  cropX: number;
  cropY: number;
  cropWidth: number;
  cropHeight: number;
}

export type AdminReadResultV1<Value> =
	| { value: Value; error?: never }
	| { error: ErrorPayload; value?: never };

export type AdminDocumentV1 = Record<string, unknown> & {
	id: string;
	createdAt?: string;
	updatedAt?: string;
	deletedAt?: string;
	_status?: "draft" | "published";
	_revision?: number;
	_localization?: { sources: Record<string, string> };
};

export interface AdminDocumentDataV1 {
	document: AdminReadResultV1<AdminDocumentV1>;
	access: AdminReadResultV1<AccessCapabilitiesEnvelope>;
}

export interface AdminCreateDataV1 {
	values: Record<string, unknown>;
	access: AdminReadResultV1<AccessCapabilitiesEnvelope>;
}


export interface DocumentVersion<Document> {
	ID: string;
	DocumentID: string;
	Revision: number;
	Status: "draft" | "published";
	Snapshot: Document;
	CreatedAt: string;
}

export interface AdminVersionsDataV1 {
	history: AdminReadResultV1<DocumentVersion<AdminDocumentV1>[]>;
	detail?: AdminReadResultV1<DocumentVersion<AdminDocumentV1>>;
	document: AdminDocumentDataV1;
}

export interface AdminSecurityDataV1 {
	sessions: AdminReadResultV1<AuthSessionInfo[]>;
	apiKeys: AdminReadResultV1<APIKeyInfo[]>;
}

export type AdminCollectionListPageV1 =
	| { value: CollectionPageEnvelope<Record<string, unknown> & { id: string }>; error?: never }
	| { error: ErrorPayload; value?: never };

export type AdminCollectionListCountV1 =
	| { value: number; error?: never }
	| { error: ErrorPayload; value?: never };

export type AdminCollectionListPreferenceV1 =
	| { value: unknown; error?: never }
	| { error: ErrorPayload; value?: never };

export interface AdminCollectionListPreferencesV1 {
	workspace: AdminCollectionListPreferenceV1;
	presets: AdminCollectionListPreferenceV1;
}

export interface AdminCollectionListDataV1 {
	query: { where?: Record<string, unknown>; countWhere?: Record<string, unknown>; locale?: string; trash: boolean };
	page?: AdminCollectionListPageV1;
	counts: Record<string, AdminCollectionListCountV1>;
	preferences?: AdminCollectionListPreferencesV1;
}

export interface AdminPreparedNavigationV1 {
	collectionOperations: Record<string, OperationCapabilities>;
	globalOperations: Record<string, OperationCapabilities>;
	contentLocale?: string;
}

export interface AdminPreparedRuntimeV1 extends AdminPreparedNavigationV1 {
	manifest: SchemaManifest;
	session?: AuthSession<Record<string, unknown>>;
	authBootstrapAvailable: boolean;
	theme: "system" | "light" | "dark";
	adminLanguage?: string;
	adminTimeZone?: string;
	preferences: Record<string, unknown>;
}

export interface AdminPreparedRouteDiagnosticV1 {
	code: string;
	message: string;
}

interface AdminPreparedRouteStateBaseV1 {
	version: typeof ADMIN_PREPARED_ROUTE_STATE_VERSION;
	pathname: string;
	search: string;
	contextKey: string;
	fingerprint: string;
	buildId: string;
	moduleGroups: string[];
	diagnostic?: AdminPreparedRouteDiagnosticV1;
	loaders?: Record<string, AdminReadResultV1<unknown>>;
}

type AdminPreparedRuntimeStateV1 =
	| { runtime: AdminPreparedRuntimeV1; navigation?: never }
	| { runtime?: never; navigation: AdminPreparedNavigationV1 };

export type AdminPreparedRouteStateV1 =
	| (AdminPreparedRouteStateBaseV1 & AdminPreparedRuntimeStateV1 & {
		outcome: "prepared";
		route: AdminPreparedRouteDataV1;
		location?: never;
	})
	| (AdminPreparedRouteStateBaseV1 & {
		outcome: "redirect";
		location: string;
		runtime?: AdminPreparedRuntimeV1;
		navigation?: AdminPreparedNavigationV1;
		route?: never;
	})
	| (AdminPreparedRouteStateBaseV1 & {
		outcome: "reload";
		runtime?: never;
		navigation?: never;
		route?: never;
		location?: never;
	})
	| (AdminPreparedRouteStateBaseV1 & {
		outcome: "fallback";
		runtime?: AdminPreparedRuntimeV1;
		navigation?: AdminPreparedNavigationV1;
		route?: never;
		location?: never;
		diagnostic: AdminPreparedRouteDiagnosticV1;
	});

export interface ValidationIssue {
	code: string;
	path: string;
	message: string;
	target?: string;
	fieldId?: string;
	collectionId?: string;
	globalId?: string;
	locale?: string;
}

/** Explicit advisory evaluation of an unsaved snapshot; never a write. */
export interface LiveValidationRequest {
	id?: string;
	data: Record<string, unknown>;
	fields: string[];
	embedded?: LiveValidationEmbeddedScope[];
}

/** A detached payload selected through Go-declared plugin metadata. */
export interface LiveValidationEmbeddedScope {
	field: string;
	treeKey: string;
	caseTag: string;
	variantSlug: string;
	identity: string;
	data: Record<string, unknown>;
}

export interface LiveValidationEvaluation {
	path: string;
	target?: string;
	status: "checked" | "skipped";
	issues: ValidationIssue[];
}

/** Advisory feedback is separate from authoritative save failures. */
export interface LiveValidationEnvelope {
	evaluations: LiveValidationEvaluation[];
}

export interface ErrorPayload {
	code: ErrorCode;
	status: number;
	message: string;
	requestId?: string;
	issues: ValidationIssue[];
	details?: unknown;
}

export interface ErrorEnvelope {
	error: ErrorPayload;
}

export interface Pagination {
	page: number;
	limit: number;
	totalDocs: number;
	totalPages: number;
	hasNextPage: boolean;
	hasPrevPage: boolean;
}

export interface PageEnvelope<Document> {
	docs: Document[];
	pagination: Pagination;
}

export interface CollectionPageAccess {
	collection: AccessCapabilitiesEnvelope;
	documents: Record<string, AccessCapabilitiesEnvelope>;
}

export interface CollectionPageEnvelope<Document> extends PageEnvelope<Document> {
	access: CollectionPageAccess;
}

export interface CountEnvelope {
	totalDocs: number;
}

export interface DocumentEnvelope<Document> {
	doc: Document;
}

export interface BulkEnvelope<Document> {
	docs: Document[];
}

export interface JoinMutationInput {
	additions: string[];
	removals: string[];
}

export interface JoinMutationEnvelope<Document> {
	doc: Document;
	added: number;
	removed: number;
}

export interface PreferenceEnvelope<Value> {
	value: Value;
}

export interface ScheduledPublication {
	timeZone?: string;
	id: string;
	action: "publish" | "unpublish";
	documentId: string;
	expectedRevision: number;
	runAt: string;
	attempts: number;
	lastError?: string;
	createdAt: string;
}

export interface ScheduledPublicationEnvelope {
	scheduledPublication: ScheduledPublication;
}

export interface ScheduledPublicationsEnvelope {
	scheduledPublications: ScheduledPublication[];
}

export interface OperationCapabilities {
	admin: boolean;
	create: boolean;
	read: boolean;
	readVersions: boolean;
	update: boolean;
	delete: boolean;
	duplicate: boolean;
	publish: boolean;
	unpublish: boolean;
	restoreDeleted: boolean;
	deletePermanent: boolean;
	selectAll: boolean;
}

export interface FieldCapabilities {
	read: boolean;
	create: boolean;
	update: boolean;
}

export interface AccessCapabilitiesEnvelope {
	operations: OperationCapabilities;
	fields: Record<string, FieldCapabilities>;
}

export interface CollectionSelectionInput<Where = Record<string, unknown>> {
	where?: Where;
	trash?: boolean;
}

export interface CollectionSelectionItem {
	id: string;
	access: AccessCapabilitiesEnvelope;
}

export interface CollectionSelectionEnvelope {
	items: CollectionSelectionItem[];
	totalDocs: number;
}

export interface DocumentLock {
	documentId: string;
	ownerId: string;
	ownerLabel: string;
	createdAt: string;
	updatedAt: string;
	expiresAt: string;
}

export interface DocumentLockEnvelope {
	lock: DocumentLock | null;
	owned: boolean;
	acquired: boolean;
	canTakeOver: boolean;
}

export interface DeleteEnvelope {
	id: string;
	deleted: boolean;
}

export interface AuthSession<User> {
	id: string;
	collection: string;
	user: User;
	expiresAt: string;
}

export interface AuthSessionInfo {
	id: string;
	createdAt: string;
	lastSeenAt: string;
	expiresAt: string;
	ipAddress?: string;
	userAgent?: string;
	current: boolean;
}

export interface AuthSessionsEnvelope {
	sessions: AuthSessionInfo[];
}

export interface SessionEnvelope<User> {
	session: AuthSession<User>;
}

export type SessionTransport = "cookie" | "token";

export interface LoginRequest {
	email: string;
	password: string;
	transport?: SessionTransport;
}

export interface SessionTokenEnvelope<User> {
	session: AuthSession<User>;
	token: string;
}

export interface LogoutEnvelope {
	loggedOut: boolean;
}

export interface AuthActionEnvelope {
	success: boolean;
}

export interface AuthBootstrapEnvelope {
	available: boolean;
}

export interface PreviewToken {
	token: string;
	resource: "collection" | "global";
	slug: string;
	documentId: string;
	expiresAt: string;
}

export interface PreviewTokenEnvelope {
	previewToken: PreviewToken;
}

export interface APIKey {
	id: string;
	name: string;
	key: string;
	createdAt: string;
	expiresAt?: string;
}

export interface APIKeyInfo {
	id: string;
	name: string;
	createdAt: string;
	lastUsedAt?: string;
	expiresAt?: string;
}

export interface APIKeyEnvelope {
	apiKey: APIKey;
}

export interface APIKeysEnvelope {
	apiKeys: APIKeyInfo[];
}

export interface SchemaManifest {
	blocks?: SchemaBlockType[];
	version: typeof SCHEMA_MANIFEST_VERSION;
	application: SchemaApplication;
	collections: SchemaCollection[];
	globals?: SchemaGlobal[];
	plugins: SchemaPlugin[];
}

export interface SchemaApplication {
	adminLoaders?: SchemaAdminLoader[];
	name: string;
	nameTranslations?: Record<string, string>;
	allowIDOnCreate?: boolean;
	admin?: SchemaAdminSettings;
	adminLocalization?: SchemaAdminLocalizationSettings;
	localization?: SchemaLocalizationSettings;
	endpoints?: SchemaEndpoint[];
}

export interface SchemaAdminLoader {
	key: string;
	input: AdminDataType;
	output: AdminDataType;
}

export interface AdminDataType {
	kind: "string" | "number" | "boolean" | "object" | "array";
	nullable?: boolean;
	optional?: boolean;
	fields?: Record<string, AdminDataType>;
	element?: AdminDataType;
}

export interface SchemaEndpoint {
	method: string;
	path: string;
	summary?: string;
}

export interface SchemaAdminLocalizationSettings {
	languages: SchemaAdminLanguage[];
	defaultLanguage: string;
	timeZones?: SchemaAdminTimeZone[];
	defaultTimeZone?: string;
}

export interface SchemaAdminLanguage {
	code: string;
	label: string;
	labelTranslations?: Record<string, string>;
	rtl?: boolean;
}

export interface SchemaAdminTimeZone {
	id: string;
	label: string;
	labelTranslations?: Record<string, string>;
}

export interface SchemaLocalizationSettings {
	locales: SchemaLocale[];
	defaultLocale: string;
	fallback: boolean;
}

export interface SchemaLocale {
	code: string;
	label: string;
	rtl?: boolean;
	fallbackLocale?: string[];
}

export interface SchemaAdminSettings {
	userCollectionId: string;
	userCollectionSlug: string;
}

export interface SchemaPlugin {
	key: string;
	version?: string;
	goPackage?: string;
	apiVersion?: number;
	ridu?: SchemaPluginCompatibility;
	admin?: SchemaPluginAdmin;
	fieldTypes?: SchemaPluginFieldType[];
	endpoints?: SchemaPluginEndpoint[];
}

export interface SchemaPluginCompatibility {
	minimum: string;
	maximumExclusive?: string;
}

export interface SchemaPluginAdmin {
	package: string;
	export: string;
	apiVersion: number;
	pairingVersion: number;
	routes?: string[];
	assets?: string[];
}

export interface SchemaPluginFieldType {
	embeddedTypes?: string[];
	key: string;
	typescriptPackage: string;
	typescriptOutput: string;
	typescriptInput: string;
	typescriptWhere?: string;
	goPackage?: string;
	goType?: string;
	jsonSchema?: unknown;
}

export interface SchemaPluginEndpoint {
	method: string;
	path: string;
	summary: string;
}

export interface SchemaCollection {
	id: string;
	slug: string;
	labels: SchemaCollectionLabels;
	admin: SchemaCollectionAdmin;
	capabilities: SchemaCapabilities;
	authSettings?: SchemaAuthSettings;
	uploadSettings?: SchemaUploadSettings;
	versionSettings?: SchemaVersionSettings;
	documentLockSettings?: SchemaDocumentLockSettings;
	fields: SchemaField[];
	indexes?: SchemaCollectionIndex[];
	endpoints?: SchemaEndpoint[];
}

export interface SchemaCollectionIndex {
	fields: string[];
	unique?: boolean;
}

export interface SchemaDocumentLockSettings {
	durationSeconds: number;
}

export interface SchemaCollectionAdmin {
	useAsTitle?: string;
	defaultColumns?: string[];
	group?: string;
	groupTranslations?: Record<string, string>;
	description?: string;
	descriptionTranslations?: Record<string, string>;
	folderField?: string;
	parentField?: string;
	livePreview?: SchemaLivePreview;
}

export interface SchemaLivePreview {
	url: string;
	breakpoints?: SchemaPreviewBreakpoint[];
}

export interface SchemaPreviewBreakpoint {
	name: string;
	label: string;
	labelTranslations?: Record<string, string>;
	width: number;
	height: number;
}

export type SchemaGlobal = SchemaCollection;

export interface SchemaAuthSettings {
	identityField: string;
	sessionDurationSeconds: number;
	passwordMinLength: number;
	passwordMaxBytes: number;
	passwordBcryptCost: number;
	maxLoginAttempts: number;
	lockDurationSeconds: number;
	passwordReset: boolean;
	passwordResetTokenDurationSeconds: number;
	verifyEmail: boolean;
	verificationTokenDurationSeconds: number;
	apiKeys: boolean;
}

export interface SchemaUploadSettings {
	maxFileSize: number;
	mimeTypes: string[];
	private: boolean;
	imageSizes?: SchemaImageSize[];
}

export interface SchemaImageSize {
	name: string;
	width: number;
	height: number;
	fit: "cover" | "contain";
}

export interface SchemaVersionSettings {
	drafts: boolean;
	maxPerDocument: number;
	autosaveIntervalSeconds: number;
}

export interface SchemaCollectionLabels {
	singular: string;
	singularTranslations?: Record<string, string>;
	plural: string;
	pluralTranslations?: Record<string, string>;
}

export interface SchemaCapabilities {
	auth: boolean;
	upload: boolean;
	versions: boolean;
	trash: boolean;
	locking: boolean;
	global?: boolean;
}

export interface SchemaField {
	id: string;
	name: string;
	path: string;
	type: FieldType;
	category: FieldCategory;
	required: boolean;
	unique: boolean;
	index?: boolean;
	localized?: boolean;
	queryRestricted?: boolean;
	default?: string;
	dynamicDefault?: boolean;
	liveValidation?: boolean;
	admin: SchemaFieldAdmin;
	text?: SchemaTextField;
	textarea?: SchemaTextField;
	code?: SchemaCodeField;
	number?: SchemaNumberField;
	list?: SchemaPrimitiveListField;
	date?: SchemaDateField;
	select?: SchemaSelectField;
	point?: SchemaPointField;
	ui?: SchemaUIField;
	join?: SchemaJoinField;
	virtual?: SchemaVirtualField;
	relationship?: SchemaRelationshipField;
	upload?: SchemaUploadField;
	nested?: SchemaNestedField;
	blocks?: SchemaBlocksField;
	plugin?: SchemaPluginField;
}

export interface SchemaFieldAdmin {
	extensions?: Record<string, unknown>;
	editor?: SchemaFieldEditor;
	label: string;
	labelTranslations?: Record<string, string>;
	description?: string;
	descriptionTranslations?: Record<string, string>;
	placeholder?: string;
	placeholderTranslations?: Record<string, string>;
	readOnly?: boolean;
	hidden?: boolean;
	sidebar?: boolean;
	columns?: number;
	row?: SchemaFieldRow;
	collapsible?: SchemaFieldCollapsible;
	tab?: string;
	tabTranslations?: Record<string, string>;
	tabGroup?: SchemaFieldTabGroup;
	namedTab?: boolean;
	condition?: SchemaFieldCondition;
	component?: SchemaFieldAdminComponent;
}

export interface SchemaFieldEditor {
	reference: string;
	config?: unknown;
}

export interface SchemaFieldAdminComponent {
	reference?: string;
	plugin?: string;
	component?: string;
	config?: unknown;
}

export interface SchemaFieldRow {
	id: string;
	extensions?: Record<string, unknown>;
}

export interface SchemaFieldCollapsible {
	id: string;
	label: string;
	labelTranslations?: Record<string, string>;
	initiallyCollapsed?: boolean;
	extensions?: Record<string, unknown>;
}

export interface SchemaFieldTabGroup {
	id: string;
	extensions?: Record<string, unknown>;
}

export type SchemaFieldCondition =
	| { kind: "all" | "any"; conditions: SchemaFieldCondition[] }
	| { kind: "not"; conditions: [SchemaFieldCondition] }
	| { kind: "predicate"; predicate: SchemaFieldConditionPredicate };

export interface SchemaFieldConditionPredicate {
	scope: "document" | "sibling";
	path: string;
	operator: "equals" | "notEquals" | "oneOf";
	values: SchemaScalarLiteral[];
}

export type SchemaScalarLiteral =
	| { type: "string"; value: string }
	| { type: "number"; value: string }
	| { type: "boolean"; value: "true" | "false" };

export interface SchemaPrimitiveListField {
	minRows?: number;
	maxRows?: number;
}

export interface SchemaTextField {
	minLength?: number;
	maxLength?: number;
	slug?: SchemaSlugField;
}

export interface SchemaSlugField {
	sourcePath: string;
}

export interface SchemaCodeField {
	language?: string;
	minLength?: number;
	maxLength?: number;
}

export interface SchemaNumberField {
	min?: number;
	max?: number;
	step?: number;
}

export type SchemaDateFormat = "date" | "date-time" | "time";

export interface SchemaDateField {
	format: SchemaDateFormat;
}

export type SchemaPointField = Record<never, never>;
export type SchemaUIField = Record<never, never>;

export interface SchemaJoinField {
	collectionId: string;
	collectionSlug: string;
	on: string;
	limit: number;
	defaultColumns?: string[];
	defaultSort?: string;
	allowCreate?: boolean;
}

export type SchemaValueType = "string" | "number" | "boolean" | "json";

export interface SchemaVirtualField {
	valueType: SchemaValueType;
}

export interface SchemaSelectField {
	options: SchemaSelectOption[];
	hasMany?: boolean;
	defaultValues?: string[];
}

export interface SchemaSelectOption {
	value: string;
	label: string;
	labelTranslations?: Record<string, string>;
}

export interface SchemaRelationshipField {
	collectionId?: string;
	collectionSlug?: string;
	targets?: SchemaRelationshipTarget[];
	hasMany?: boolean;
	polymorphic?: boolean;
	optionFilters?: SchemaRelationshipFilter[];
	onDelete: SchemaReferenceDeleteAction;
}

export type SchemaReferenceDeleteAction = "nullify" | "restrict";

export interface SchemaRelationshipFilter {
	collectionSlug?: string;
	targetPath: string;
	operator?: "equals" | "notEquals" | "like" | "contains" | "greaterThan" | "greaterThanEqual" | "lessThan" | "lessThanEqual";
	sourcePath?: string;
	value?: SchemaScalarLiteral;
}

export interface SchemaRelationshipTarget {
	collectionId: string;
	collectionSlug: string;
}

export interface SchemaUploadField {
	collectionId: string;
	collectionSlug: string;
	hasMany?: boolean;
	optionFilters?: SchemaRelationshipFilter[];
	onDelete: SchemaReferenceDeleteAction;
}

export interface SchemaNestedField {
	fields: SchemaField[];
	minRows?: number;
	maxRows?: number;
	rowLabel?: string;
	rowLabelComponent?: SchemaFieldAdminComponent;
	rowLabels?: SchemaArrayRowLabels;
}

export interface SchemaArrayRowLabels {
	singular: string;
	singularTranslations?: Record<string, string>;
	plural: string;
	pluralTranslations?: Record<string, string>;
}

export interface SchemaBlocksField {
	minRows?: number;
	maxRows?: number;
	types?: SchemaBlockType[];
	blockReferences?: string[];
}

export interface SchemaBlockLabels {
	singular: string;
	plural: string;
	singularTranslations?: Record<string, string>;
	pluralTranslations?: Record<string, string>;
}

export interface SchemaBlockType {
	typeName?: string;
	admin?: { nameField?: string; rowLabel?: string };
	slug: string;
	labels: SchemaBlockLabels;
	fields: SchemaField[];
}

export interface SchemaEmbeddedTree {
	version: number;
	key: string;
	root: string[];
	children: string;
	tag: string;
	cases: SchemaEmbeddedTreeCase[];
}

export interface SchemaEmbeddedTreeCase {
	tagValue: string;
	payload: string;
	discriminator: string;
	identity: string;
	types?: SchemaBlockType[];
	blockReferences?: string[];
}

export interface SchemaPluginField {
	embeddedTrees?: SchemaEmbeddedTree[];
	key: string;
	config: unknown;
	referenceKeys?: string[];
}

export interface SchemaEnvelope {
	schema: SchemaManifest;
}
`) + "\n"
