// Code generated by Ridu from ridu.schema.json. DO NOT EDIT.

import { createClient as createRuntimeClient } from "@riducms/sdk";
import type { AuthCollectionSlug, ClientOptions, RiduClient } from "@riducms/sdk";

export type ID = string;

import { createAdminLoader } from "@riducms/sdk";

export interface AdminLoaderInputs {
	"editorial-dashboard": { "q"?: string };
	"editorial-view": { "q"?: string };
}

export interface AdminLoaderData {
	"editorial-dashboard": { "categories": number; "posts": number; "search": string };
	"editorial-view": { "documents": Array<{ "id": string; "title": string }> | null; "locale": string; "pathname": string; "search": string };
}

export const adminLoaders = {
	"editorial-dashboard": createAdminLoader<AdminLoaderInputs["editorial-dashboard"], AdminLoaderData["editorial-dashboard"]>({"key":"editorial-dashboard","input":{"kind":"object","fields":{"q":{"kind":"string"}}},"output":{"kind":"object","fields":{"categories":{"kind":"number"},"posts":{"kind":"number"},"search":{"kind":"string"}}}}),
	"editorial-view": createAdminLoader<AdminLoaderInputs["editorial-view"], AdminLoaderData["editorial-view"]>({"key":"editorial-view","input":{"kind":"object","fields":{"q":{"kind":"string"}}},"output":{"kind":"object","fields":{"documents":{"kind":"array","nullable":true,"element":{"kind":"object","fields":{"id":{"kind":"string"},"title":{"kind":"string"}}}},"locale":{"kind":"string"},"pathname":{"kind":"string"},"search":{"kind":"string"}}}}),
} as const;

export interface ScalarWhere<Value> {
	equals?: Value;
	notEquals?: Value;
	greaterThan?: Value;
	greaterThanEqual?: Value;
	lessThan?: Value;
	lessThanEqual?: Value;
	contains?: Value extends string ? string : never;
	like?: Value extends string ? string : never;
	in?: readonly Value[];
	exists?: boolean;
}

export type TimestampWhere = Omit<ScalarWhere<string>, "contains" | "like">;

/** Item membership for lists, multi-selects, reference lists and polymorphic relationships; wrap `in` in `not` to exclude. */
export interface MembershipWhere<Value> {
	in?: readonly Value[];
	equals?: null;
	notEquals?: null;
	exists?: boolean;
}

export interface ExistsWhere {
	exists?: boolean;
}

export interface Pages {
	id: ID;
	createdAt: string;
	updatedAt: string;
	"title"?: string | null;
}

export interface PagesCreate {
	"title"?: string | null;
}

export interface PagesUpdate {
	"title"?: string | null;
}

export interface PagesWhere {
	and?: readonly PagesWhere[];
	or?: readonly PagesWhere[];
	not?: PagesWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	"title"?: ScalarWhere<string>;
}

export interface PagesSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"title"?: boolean;
}

export interface PagesPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"title"?: boolean;
}

export type PagesPopulate = Record<string, never>;

export type PagesValidationPath = "title";

export interface RiduConfig {
	locale: never;
	collections: {
		"pages": {
			slug: "pages";
			auth: false;
			upload: false;
			versions: false;
			drafts: false;
			trash: false;
			output: Pages;
			create: PagesCreate;
			update: PagesUpdate;
			where: PagesWhere;
			select: PagesSelect;
			populate: PagesPopulate;
			validationPath: PagesValidationPath;
		};
	};
}

export type CollectionSlug = keyof RiduConfig["collections"];

export function createClient<const DefaultAuth extends AuthCollectionSlug<RiduConfig> = never>(
	options: ClientOptions<DefaultAuth>
): RiduClient<RiduConfig, DefaultAuth> {
	return createRuntimeClient<RiduConfig, DefaultAuth>(options);
}
