// Code generated by Ridu from ridu.schema.json. DO NOT EDIT.

import { createClient as createRuntimeClient } from "@riducms/sdk";
import type { AuthCollectionSlug, ClientOptions, RiduClient } from "@riducms/sdk";

export type ID = string;

export interface ScalarWhere<Value> {
	equals?: Value;
	notEquals?: Value;
	greaterThan?: Value;
	greaterThanEqual?: Value;
	lessThan?: Value;
	lessThanEqual?: Value;
	contains?: Value extends string ? string : never;
	like?: Value extends string ? string : never;
	in?: readonly Value[];
	exists?: boolean;
}

export type TimestampWhere = Omit<ScalarWhere<string>, "contains" | "like">;

/** Item membership for lists, multi-selects, reference lists and polymorphic relationships; wrap `in` in `not` to exclude. */
export interface MembershipWhere<Value> {
	in?: readonly Value[];
	equals?: null;
	notEquals?: null;
	exists?: boolean;
}

export interface ExistsWhere {
	exists?: boolean;
}

export type PostsBodyBlocksBlockBlockInput = never;
export type PostsBodyBlocksBlockInput = Array<PostsBodyBlocksBlockBlockInput>;

export type PostsBodyBlocksBlockBlockUpdate = never;
export type PostsBodyBlocksBlockUpdate = Array<PostsBodyBlocksBlockBlockUpdate>;

export type PostsBodyBlocksBlockBlock = never;
export type PostsBodyBlocksBlock = Array<PostsBodyBlocksBlockBlock>;

export interface Posts {
	id: ID;
	createdAt: string;
	updatedAt: string;
	"title"?: string;
	"body"?: import("@riducms/sdk/richtext").RichTextDocument<never[][number]> | null;
}

export interface PostsCreate {
	"title": string;
	"body"?: import("@riducms/sdk/richtext").RichTextDocumentInput<never[][number]> | null;
}

export interface PostsUpdate {
	"title"?: string;
	"body"?: import("@riducms/sdk/richtext").RichTextDocumentInput<never[][number]> | null;
}

export interface PostsWhere {
	and?: readonly PostsWhere[];
	or?: readonly PostsWhere[];
	not?: PostsWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	"title"?: ScalarWhere<string>;
	"body"?: ScalarWhere<import("@riducms/sdk/richtext").RichTextDocument<never[][number]>>;
}

export interface PostsSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"title"?: boolean;
	"body"?: boolean;
}

export interface PostsPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"title"?: boolean;
	"body"?: boolean;
}

export type PostsPopulate = Record<string, never>;

export type PostsValidationPath = "title" | "body" | `body.${string}`;

export interface RiduConfig {
	locale: never;
	collections: {
		"posts": {
			slug: "posts";
			auth: false;
			upload: false;
			versions: false;
			drafts: false;
			trash: false;
			output: Posts;
			create: PostsCreate;
			update: PostsUpdate;
			where: PostsWhere;
			select: PostsSelect;
			populate: PostsPopulate;
			validationPath: PostsValidationPath;
		};
	};
}

export type CollectionSlug = keyof RiduConfig["collections"];

export function createClient<const DefaultAuth extends AuthCollectionSlug<RiduConfig> = never>(
	options: ClientOptions<DefaultAuth>
): RiduClient<RiduConfig, DefaultAuth> {
	return createRuntimeClient<RiduConfig, DefaultAuth>(options);
}
