// Code generated by Ridu. DO NOT EDIT.
import { resolveAdminPluginPairs, type PluginFieldRegistration } from "@riducms/plugin";
type RiduNamedFieldComponent = import("@riducms/plugin").RegisteredPluginField & { readonly type: Exclude<import("@riducms/plugin").RegisteredPluginField["type"], "plugin"> }
 | (PluginFieldRegistration<import("@riducms/plugin-richtext/document").RichTextDocument<unknown>, import("@riducms/plugin-richtext/document").RichTextDocumentInput<unknown>, "plugin"> & { readonly fieldType: "richtext" });
import { richTextAdminPlugin as riduAdminPlugin0 } from "@riducms/plugin-richtext";
riduAdminPlugin0.fields["richtext"] satisfies PluginFieldRegistration<import("@riducms/plugin-richtext/document").RichTextDocument<unknown>, import("@riducms/plugin-richtext/document").RichTextDocumentInput<unknown>>;
riduAdminPlugin0 satisfies { readonly key: string; readonly components?: Readonly<Record<string, RiduNamedFieldComponent>> };

const resolvedAdminPluginPairs = resolveAdminPluginPairs([
	{
		backend: { key: "richtext", package: "@riducms/plugin-richtext", export: "richTextAdminPlugin", apiVersion: 1, pairingVersion: 1, routes: [], assets: [], fieldTypes: ["richtext"] },
		admin: riduAdminPlugin0,
	},
]);

export const generatedAdminPlugins = resolvedAdminPluginPairs.plugins;
