// Code generated by Ridu. DO NOT EDIT.
import { resolveAdminPluginPairs } from "@riducms/plugin";
import { richTextAdminPlugin as riduAdminPlugin0 } from "@riducms/plugin-richtext";

const resolvedAdminPluginPairs = resolveAdminPluginPairs([
	{
		backend: { key: "richtext", package: "@riducms/plugin-richtext", export: "richTextAdminPlugin", apiVersion: 1, pairingVersion: 1, routes: [], assets: [] },
		admin: riduAdminPlugin0,
	},
]);

export const generatedAdminPlugins = resolvedAdminPluginPairs.plugins;
