// Code generated by Ridu from Go protocol contracts. DO NOT EDIT.

export const PROTOCOL_VERSION = 1 as const;

export type ErrorCode =
	| "validation"
	| "access_denied"
	| "not_found"
	| "conflict"
	| "delete_restricted"
	| "bad_request"
	| "internal"
	| "rate_limited"
	| "email_not_verified"
	| "auth_feature_disabled"
	| "invalid_auth_token"
	| "invalid_preview_token"
	| "selection_too_large";

export type FieldType =
	| "text"
	| "code"
	| "select"
	| "radio"
	| "point"
	| "ui"
	| "join"
	| "virtual"
	| "relationship"
	| "upload"
	| "group"
	| "textarea"
	| "email"
	| "date"
	| "number"
	| "checkbox"
	| "json"
	| "array"
	| "blocks"
	| "plugin";

export type FieldCategory =
	| "scalar"
	| "nested"
	| "presentation"
	| "relationship"
	| "upload"
	| "plugin";

export const SCHEMA_MANIFEST_VERSION = 1 as const;

export const ADMIN_PLUGIN_API_VERSION = 1 as const;

export interface ValidationIssue {
	code: string;
	path: string;
	message: string;
}

export interface ErrorPayload {
	code: ErrorCode;
	status: number;
	message: string;
	requestId?: string;
	issues: ValidationIssue[];
	details?: unknown;
}

export interface ErrorEnvelope {
	error: ErrorPayload;
}

export interface Pagination {
	page: number;
	limit: number;
	totalDocs: number;
	totalPages: number;
	hasNextPage: boolean;
	hasPrevPage: boolean;
}

export interface PageEnvelope<Document> {
	docs: Document[];
	pagination: Pagination;
}

export interface CountEnvelope {
	totalDocs: number;
}

export interface DocumentEnvelope<Document> {
	doc: Document;
}

export interface BulkEnvelope<Document> {
	docs: Document[];
}

export interface JoinMutationInput {
	additions: string[];
	removals: string[];
}

export interface JoinMutationEnvelope<Document> {
	doc: Document;
	added: number;
	removed: number;
}

export interface PreferenceEnvelope<Value> {
	value: Value;
}

export interface ScheduledPublish {
	id: string;
	documentId: string;
	expectedRevision: number;
	runAt: string;
	attempts: number;
	lastError?: string;
	createdAt: string;
}

export interface ScheduledPublishEnvelope {
	scheduledPublish: ScheduledPublish;
}

export interface ScheduledPublishesEnvelope {
	scheduledPublishes: ScheduledPublish[];
}

export interface OperationCapabilities {
	admin: boolean;
	create: boolean;
	read: boolean;
	readVersions: boolean;
	update: boolean;
	delete: boolean;
	duplicate: boolean;
	publish: boolean;
	unpublish: boolean;
	restoreDeleted: boolean;
	deletePermanent: boolean;
	selectAll: boolean;
}

export interface FieldCapabilities {
	read: boolean;
	create: boolean;
	update: boolean;
}

export interface AccessCapabilitiesEnvelope {
	operations: OperationCapabilities;
	fields: Record<string, FieldCapabilities>;
}

export interface CollectionSelectionInput<Where = Record<string, unknown>> {
	where?: Where;
	trash?: boolean;
}

export interface CollectionSelectionItem {
	id: string;
	access: AccessCapabilitiesEnvelope;
}

export interface CollectionSelectionEnvelope {
	items: CollectionSelectionItem[];
	totalDocs: number;
}

export interface DocumentLock {
	documentId: string;
	ownerId: string;
	ownerLabel: string;
	createdAt: string;
	updatedAt: string;
	expiresAt: string;
}

export interface DocumentLockEnvelope {
	lock: DocumentLock | null;
	owned: boolean;
	acquired: boolean;
	canTakeOver: boolean;
}

export interface DeleteEnvelope {
	id: string;
	deleted: boolean;
}

export interface AuthSession<User> {
	id: string;
	collection: string;
	user: User;
	expiresAt: string;
}

export interface AuthSessionInfo {
	id: string;
	createdAt: string;
	lastSeenAt: string;
	expiresAt: string;
	ipAddress?: string;
	userAgent?: string;
	current: boolean;
}

export interface AuthSessionsEnvelope {
	sessions: AuthSessionInfo[];
}

export interface SessionEnvelope<User> {
	session: AuthSession<User>;
}

export interface LogoutEnvelope {
	loggedOut: boolean;
}

export interface AuthActionEnvelope {
	success: boolean;
}

export interface AuthBootstrapEnvelope {
	available: boolean;
}

export interface PreviewToken {
	token: string;
	resource: "collection" | "global";
	slug: string;
	documentId: string;
	expiresAt: string;
}

export interface PreviewTokenEnvelope {
	previewToken: PreviewToken;
}

export interface APIKey {
	id: string;
	name: string;
	key: string;
	createdAt: string;
	expiresAt?: string;
}

export interface APIKeyInfo {
	id: string;
	name: string;
	createdAt: string;
	lastUsedAt?: string;
	expiresAt?: string;
}

export interface APIKeyEnvelope {
	apiKey: APIKey;
}

export interface APIKeysEnvelope {
	apiKeys: APIKeyInfo[];
}

export interface SchemaManifest {
	version: typeof SCHEMA_MANIFEST_VERSION;
	application: SchemaApplication;
	collections: SchemaCollection[];
	globals?: SchemaGlobal[];
	plugins: SchemaPlugin[];
}

export interface SchemaApplication {
	name: string;
	nameTranslations?: Record<string, string>;
	allowIDOnCreate?: boolean;
	admin?: SchemaAdminSettings;
	adminLocalization?: SchemaAdminLocalizationSettings;
	localization?: SchemaLocalizationSettings;
	endpoints?: SchemaEndpoint[];
}

export interface SchemaEndpoint {
	method: string;
	path: string;
	summary?: string;
}

export interface SchemaAdminLocalizationSettings {
	languages: SchemaAdminLanguage[];
	defaultLanguage: string;
	timeZones?: SchemaAdminTimeZone[];
	defaultTimeZone?: string;
}

export interface SchemaAdminLanguage {
	code: string;
	label: string;
	labelTranslations?: Record<string, string>;
	rtl?: boolean;
}

export interface SchemaAdminTimeZone {
	id: string;
	label: string;
	labelTranslations?: Record<string, string>;
}

export interface SchemaLocalizationSettings {
	locales: SchemaLocale[];
	defaultLocale: string;
	fallback: boolean;
}

export interface SchemaLocale {
	code: string;
	label: string;
	rtl?: boolean;
	fallbackLocale?: string[];
}

export interface SchemaAdminSettings {
	userCollectionId: string;
	userCollectionSlug: string;
}

export interface SchemaPlugin {
	key: string;
	version?: string;
	goPackage?: string;
	apiVersion?: number;
	ridu?: SchemaPluginCompatibility;
	admin?: SchemaPluginAdmin;
	fieldTypes?: SchemaPluginFieldType[];
	databaseContributions?: SchemaPluginDatabaseContribution[];
	endpoints?: SchemaPluginEndpoint[];
}

export interface SchemaPluginCompatibility {
	minimum: string;
	maximumExclusive?: string;
}

export interface SchemaPluginAdmin {
	package: string;
	export: string;
	apiVersion: number;
	pairingVersion: number;
	routes?: string[];
	assets?: string[];
}

export interface SchemaPluginFieldType {
	key: string;
	typescriptPackage: string;
	typescriptOutput: string;
	typescriptInput: string;
	typescriptWhere?: string;
	goPackage?: string;
	goType?: string;
	jsonSchema?: unknown;
}

export interface SchemaPluginMigration {
	version: number;
	name: string;
	upSQL: string[];
	downSQL: string[];
}

export type SchemaPluginDatabaseAdapter = 'postgres' | 'sqlite';

export interface SchemaPluginDatabaseContribution {
	adapter: SchemaPluginDatabaseAdapter;
	migrations?: SchemaPluginMigration[];
	tables?: string[];
}

export interface SchemaPluginEndpoint {
	method: string;
	path: string;
	summary: string;
}

export interface SchemaCollection {
	id: string;
	slug: string;
	labels: SchemaCollectionLabels;
	admin: SchemaCollectionAdmin;
	capabilities: SchemaCapabilities;
	authSettings?: SchemaAuthSettings;
	uploadSettings?: SchemaUploadSettings;
	versionSettings?: SchemaVersionSettings;
	documentLockSettings?: SchemaDocumentLockSettings;
	fields: SchemaField[];
	indexes?: SchemaCollectionIndex[];
	endpoints?: SchemaEndpoint[];
}

export interface SchemaCollectionIndex {
	fields: string[];
	unique?: boolean;
}

export interface SchemaDocumentLockSettings {
	durationSeconds: number;
}

export interface SchemaCollectionAdmin {
	useAsTitle?: string;
	defaultColumns?: string[];
	group?: string;
	groupTranslations?: Record<string, string>;
	description?: string;
	descriptionTranslations?: Record<string, string>;
	folderField?: string;
	parentField?: string;
	livePreview?: SchemaLivePreview;
}

export interface SchemaLivePreview {
	url: string;
	breakpoints?: SchemaPreviewBreakpoint[];
}

export interface SchemaPreviewBreakpoint {
	name: string;
	label: string;
	labelTranslations?: Record<string, string>;
	width: number;
	height: number;
}

export type SchemaGlobal = SchemaCollection;

export interface SchemaAuthSettings {
	identityField: string;
	sessionDurationSeconds: number;
	passwordMinLength: number;
	passwordMaxBytes: number;
	passwordBcryptCost: number;
	maxLoginAttempts: number;
	lockDurationSeconds: number;
	passwordReset: boolean;
	passwordResetTokenDurationSeconds: number;
	verifyEmail: boolean;
	verificationTokenDurationSeconds: number;
	apiKeys: boolean;
}

export interface SchemaUploadSettings {
	maxFileSize: number;
	mimeTypes: string[];
	private: boolean;
	imageSizes?: SchemaImageSize[];
}

export interface SchemaImageSize {
	name: string;
	width: number;
	height: number;
	fit: "cover" | "contain";
}

export interface SchemaVersionSettings {
	drafts: boolean;
	maxPerDocument: number;
	autosaveIntervalSeconds: number;
}

export interface SchemaCollectionLabels {
	singular: string;
	singularTranslations?: Record<string, string>;
	plural: string;
	pluralTranslations?: Record<string, string>;
}

export interface SchemaCapabilities {
	auth: boolean;
	upload: boolean;
	versions: boolean;
	trash: boolean;
	locking: boolean;
	global?: boolean;
}

export interface SchemaField {
	id: string;
	name: string;
	path: string;
	type: FieldType;
	category: FieldCategory;
	required: boolean;
	unique: boolean;
	index?: boolean;
	localized?: boolean;
	default?: string;
	admin: SchemaFieldAdmin;
	text?: SchemaTextField;
	textarea?: SchemaTextField;
	code?: SchemaCodeField;
	number?: SchemaNumberField;
	date?: SchemaDateField;
	select?: SchemaSelectField;
	point?: SchemaPointField;
	ui?: SchemaUIField;
	join?: SchemaJoinField;
	virtual?: SchemaVirtualField;
	relationship?: SchemaRelationshipField;
	upload?: SchemaUploadField;
	nested?: SchemaNestedField;
	blocks?: SchemaBlocksField;
	plugin?: SchemaPluginField;
}

export interface SchemaFieldAdmin {
	label: string;
	labelTranslations?: Record<string, string>;
	description?: string;
	descriptionTranslations?: Record<string, string>;
	placeholder?: string;
	placeholderTranslations?: Record<string, string>;
	readOnly?: boolean;
	hidden?: boolean;
	sidebar?: boolean;
	columns?: number;
	row?: SchemaFieldRow;
	collapsible?: SchemaFieldCollapsible;
	tab?: string;
	tabTranslations?: Record<string, string>;
	tabGroup?: SchemaFieldTabGroup;
	namedTab?: boolean;
	condition?: SchemaFieldCondition;
	component?: SchemaFieldAdminComponent;
}

export interface SchemaFieldAdminComponent {
	plugin: string;
	component: string;
	config?: unknown;
}

export interface SchemaFieldRow {
	id: string;
}

export interface SchemaFieldCollapsible {
	id: string;
	label: string;
	labelTranslations?: Record<string, string>;
	initiallyCollapsed?: boolean;
}

export interface SchemaFieldTabGroup {
	id: string;
}

export type SchemaFieldCondition =
	| { kind: "all" | "any"; conditions: SchemaFieldCondition[] }
	| { kind: "not"; conditions: [SchemaFieldCondition] }
	| { kind: "predicate"; predicate: SchemaFieldConditionPredicate };

export interface SchemaFieldConditionPredicate {
	scope: "document" | "sibling";
	path: string;
	operator: "equals" | "notEquals" | "oneOf";
	values: SchemaFieldConditionValue[];
}

export type SchemaFieldConditionValue =
	| { type: "string"; value: string }
	| { type: "number"; value: string }
	| { type: "boolean"; value: "true" | "false" };

export interface SchemaTextField {
	minLength?: number;
	maxLength?: number;
	slug?: SchemaSlugField;
}

export interface SchemaSlugField {
	sourcePath: string;
}

export interface SchemaCodeField {
	language?: string;
	minLength?: number;
	maxLength?: number;
}

export interface SchemaNumberField {
	min?: number;
	max?: number;
	step?: number;
}

export type SchemaDatePickerAppearance = "dayOnly" | "dayAndTime" | "timeOnly";

export interface SchemaDateField {
	pickerAppearance: SchemaDatePickerAppearance;
}

export type SchemaPointField = Record<never, never>;
export type SchemaUIField = Record<never, never>;

export interface SchemaJoinField {
	collectionId: string;
	collectionSlug: string;
	on: string;
	limit: number;
	defaultColumns?: string[];
	defaultSort?: string;
	allowCreate?: boolean;
}

export type SchemaValueType = "string" | "number" | "boolean" | "json";

export interface SchemaVirtualField {
	valueType: SchemaValueType;
}

export interface SchemaSelectField {
	choices: SchemaSelectChoice[];
	hasMany?: boolean;
	defaultValues?: string[];
}

export interface SchemaSelectChoice {
	value: string;
	label: string;
	labelTranslations?: Record<string, string>;
}

export interface SchemaRelationshipField {
	collectionId?: string;
	collectionSlug?: string;
	targets?: SchemaRelationshipTarget[];
	hasMany?: boolean;
	polymorphic?: boolean;
	optionFilters?: SchemaRelationshipFilter[];
	onDelete: SchemaReferenceDeleteAction;
}

export type SchemaReferenceDeleteAction = "nullify" | "restrict";

export interface SchemaRelationshipFilter {
	collectionSlug?: string;
	targetPath: string;
	operator?: "equals" | "notEquals" | "like" | "contains" | "greaterThan" | "greaterThanEqual" | "lessThan" | "lessThanEqual";
	sourcePath?: string;
	value?: SchemaRelationshipFilterValue;
}

export interface SchemaRelationshipFilterValue {
	type: "string" | "number" | "boolean";
	value: string;
}

export interface SchemaRelationshipTarget {
	collectionId: string;
	collectionSlug: string;
}

export interface SchemaUploadField {
	collectionId: string;
	collectionSlug: string;
	hasMany?: boolean;
	optionFilters?: SchemaRelationshipFilter[];
	onDelete: SchemaReferenceDeleteAction;
}

export interface SchemaNestedField {
	fields: SchemaField[];
	minRows?: number;
	maxRows?: number;
	rowLabel?: string;
	rowLabelComponent?: SchemaFieldAdminComponent;
	rowLabels?: SchemaArrayRowLabels;
}

export interface SchemaArrayRowLabels {
	singular: string;
	singularTranslations?: Record<string, string>;
	plural: string;
	pluralTranslations?: Record<string, string>;
}

export interface SchemaBlocksField {
	types: SchemaBlockType[];
}

export interface SchemaBlockType {
	key: string;
	label: string;
	labelTranslations?: Record<string, string>;
	fields: SchemaField[];
}

export interface SchemaPluginField {
	key: string;
	config: unknown;
	referenceKeys?: string[];
}

export interface SchemaEnvelope {
	schema: SchemaManifest;
}
