// Code generated by the Ridu project scaffold. Edit admin/, not this file.

// Package adminassets embeds this application's customized Ridu admin.
package adminassets

import (
	"embed"
	"io/fs"
)

//go:embed dist
var distribution embed.FS

func FS() fs.FS {
	root, err := fs.Sub(distribution, "dist")
	if err != nil {
		panic(err)
	}
	return root
}
