package main

import (
	"bytes"
	"context"
	"fmt"
	"image"
	"image/color"
	"image/png"

	"github.com/riducms/ridu"
	"github.com/riducms/ridu/plugins/richtext"
	"github.com/riducms/ridu/store"
)

type fixtureSeed struct {
	Administrator store.Document
	Editor        store.Document
	Contributor   store.Document
	PublishedPost store.Document
	DraftPost     store.Document
	Form          store.Document
	Submission    store.Document
}

func seedFixture(ctx context.Context, application *ridu.App) (fixtureSeed, error) {
	bootstrap := &store.Document{ID: "fixture-bootstrap", Values: store.Values{"role": store.String(roleAdministrator)}}
	administrator, err := createUser(ctx, application, bootstrap, "users_1", store.Values{
		"name":         store.String("Ridu Administrator"),
		"email":        store.String("admin@riducms.test"),
		"contactEmail": store.String("admin@example.test"),
		"role":         store.String(roleAdministrator),
		"privateNotes": store.String("Can see protected fields and perform destructive operations."),
		"profile": store.Object(store.Values{
			"bio": store.String("Maintains the complete editorial fixture."), "location": store.String("London"),
			"timezone": store.String("Europe/London"), "availableForReview": store.Boolean(true),
		}),
	}, "ridu-admin")
	if err != nil {
		return fixtureSeed{}, err
	}
	editor, err := createUser(ctx, application, &administrator, "users_2", store.Values{
		"name": store.String("Ridu Editor"), "email": store.String("editor@riducms.test"),
		"contactEmail": store.String("editor@example.test"), "role": store.String(roleEditor),
		"profile": store.Object(store.Values{
			"bio": store.String("Reviews and publishes the fixture content."), "location": store.String("Bristol"),
			"timezone": store.String("Europe/London"), "availableForReview": store.Boolean(true),
		}),
	}, "ridu-browser")
	if err != nil {
		return fixtureSeed{}, err
	}
	contributor, err := createUser(ctx, application, &administrator, "users_3", store.Values{
		"name": store.String("Demo Author"), "email": store.String("demo@riducms.local"),
		"contactEmail": store.String("author@example.test"), "role": store.String(roleContributor),
		"profile": store.Object(store.Values{
			"bio": store.String("Can edit only their own content."), "location": store.String("Cardiff"),
			"timezone": store.String("Europe/London"), "availableForReview": store.Boolean(false),
		}),
	}, "ridu-demo")
	if err != nil {
		return fixtureSeed{}, err
	}
	news, err := application.Local().Import(ctx, "categories", store.Values{
		"name": store.String("News"), "slug": store.String("news"),
		"seo": store.Object(store.Values{"title": store.String("Ridu news"), "description": store.String("Product and framework updates.")}),
	}, ridu.ImportOptions{ID: "categories_4", Status: store.StatusPublished}, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed category: %w", err)
	}
	guides, err := application.Local().Import(ctx, "categories", store.Values{
		"name": store.String("Guides"), "slug": store.String("guides"),
	}, ridu.ImportOptions{ID: "categories_5", Status: store.StatusPublished}, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed category: %w", err)
	}

	cover, err := uploadFixtureImage(ctx, application, &editor, "ridu-cover.png", color.RGBA{R: 236, G: 91, B: 67, A: 255}, store.Values{
		"alt": store.String("Warm orange Ridu cover"), "caption": store.String("Generated by the deterministic admin fixture."),
		"credit": store.String(editor.ID), "kind": store.String("illustration"),
		"tags": store.List(store.Object(store.Values{"_key": store.String("media-tag-ridu"), "label": store.String("Ridu")})),
	})
	if err != nil {
		return fixtureSeed{}, err
	}
	fieldNotes, err := uploadFixtureImage(ctx, application, &editor, "field-notes.png", color.RGBA{R: 58, G: 92, B: 82, A: 255}, store.Values{
		"alt": store.String("Green field notes cover"), "credit": store.String(contributor.ID), "kind": store.String("screenshot"),
	})
	if err != nil {
		return fixtureSeed{}, err
	}

	draftPost, err := application.Local().Import(ctx, "posts", store.Values{
		"title": store.String("  Relationship field notes  "), "slug": store.String("relationship-field-notes"),
		"summary": store.String("A contributor-owned draft used to verify filtered collection access."),
		"author":  store.String(contributor.ID), "category": store.String(guides.ID), "status": store.String("draft"),
		"featured": store.Boolean(false), "readingMinutes": store.Number(4), "cover": store.String(fieldNotes.ID),
		"content":       richDocument("Relationship selection should respect access rules and hydrate labels."),
		"collaborators": store.List(store.String(editor.ID)),
		"links": store.List(store.Object(store.Values{
			"_key": store.String("link-roadmap"), "label": store.String("Payload parity roadmap"),
			"url": store.String("/docs/internals/payload-parity"), "newWindow": store.Boolean(false),
		})),
		"layout": store.List(store.Object(store.Values{
			"_key": store.String("block-note"), "blockType": store.String("callout"), "tone": store.String("note"),
			"body": store.String("This row proves blocks preserve a stable key and discriminator."),
		})),
		"metadata": store.Object(store.Values{"fixture": store.Boolean(true), "priority": store.Number(2)}),
	}, ridu.ImportOptions{ID: "posts_8", Status: store.StatusDraft}, &contributor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed draft post: %w", err)
	}

	publishedPost, err := application.Local().Import(ctx, "posts", store.Values{
		"title": store.String("Welcome to Ridu"), "slug": store.String("welcome-to-ridu"),
		"summary": store.String("A broad browser contract for the embedded admin."),
		"author":  store.String(editor.ID), "category": store.String(news.ID), "status": store.String("published"),
		"featured": store.Boolean(true), "readingMinutes": store.Number(7), "publishDate": store.String("2026-08-13T08:00:00Z"),
		"cover": store.String(cover.ID), "gallery": store.List(store.String(cover.ID), store.String(fieldNotes.ID)),
		"content":       richDocument("Ridu keeps executable Go configuration as the source of truth."),
		"collaborators": store.List(store.String(administrator.ID), store.String(contributor.ID)),
		"relatedPosts":  store.List(store.String(draftPost.ID)),
		"seo": store.Object(store.Values{
			"title": store.String("Ridu admin fixture"), "canonicalURL": store.String("https://example.test/welcome-to-ridu"),
			"description": store.String("See every implemented field family in one document."), "socialImage": store.String(cover.ID),
		}),
		"layout": store.List(
			store.Object(store.Values{"_key": store.String("block-quote"), "blockType": store.String("quote"), "quote": store.String("One binary, one contract."), "attribution": store.String("Ridu")}),
			store.Object(store.Values{"_key": store.String("block-related"), "blockType": store.String("related-posts"), "posts": store.List(store.String(draftPost.ID))}),
		),
		"internalNotes": store.String("This is deliberately redacted for non-administrators."),
	}, ridu.ImportOptions{ID: "posts_9", Status: store.StatusDraft}, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed published post: %w", err)
	}
	publishedPost, err = application.Local().Publish(ctx, "posts", publishedPost.ID, publishedPost.Revision, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("publish post: %w", err)
	}

	page, err := application.Local().Import(ctx, "pages", store.Values{
		"title": store.String("About Ridu"), "slug": store.String("about"), "template": store.String("landing"),
		"layout": store.List(
			store.Object(store.Values{
				"_key": store.String("page-hero"), "blockType": store.String("hero"), "heading": store.String("A Go CMS with a Svelte admin"),
				"lede": store.String("Familiar where it helps; simpler where it matters."), "image": store.String(cover.ID),
			}),
			store.Object(store.Values{"_key": store.String("page-copy"), "blockType": store.String("rich-text"), "body": richDocument("This rich-text field is nested inside a block.")}),
			store.Object(store.Values{"_key": store.String("page-post"), "blockType": store.String("featured-post"), "post": store.String(publishedPost.ID)}),
		),
		"navigation": store.Object(store.Values{"label": store.String("About"), "showInHeader": store.Boolean(true), "showInFooter": store.Boolean(true)}),
	}, ridu.ImportOptions{ID: "pages_10", Status: store.StatusDraft}, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed page: %w", err)
	}
	if _, err := application.Local().Publish(ctx, "pages", page.ID, page.Revision, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("publish page: %w", err)
	}
	if _, err := application.Local().Import(ctx, "pages", store.Values{
		"title": store.String("Unreleased page"),
		"layout": store.List(store.Object(store.Values{
			"_key": store.String("draft-page-hero"), "blockType": store.String("hero"), "heading": store.String("Still being reviewed"),
		})),
	}, ridu.ImportOptions{ID: "pages_draft", Status: store.StatusDraft}, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed draft page: %w", err)
	}
	contactForm, err := application.Local().CreateWithOptions(ctx, "forms", store.Values{
		"title":               store.String("Contact Form"),
		"submitButtonLabel":   store.String("Send message"),
		"confirmationType":    store.String("message"),
		"confirmationMessage": store.String("Thanks — your message has been received."),
		"fields": store.List(
			store.Object(store.Values{
				"_key": store.String("form-name"), "blockType": store.String("text"), "name": store.String("name"),
				"label": store.String("Name"), "width": store.Number(50), "required": store.Boolean(true),
			}),
			store.Object(store.Values{
				"_key": store.String("form-email"), "blockType": store.String("email"), "name": store.String("email"),
				"label": store.String("Email"), "width": store.Number(50), "required": store.Boolean(true),
			}),
			store.Object(store.Values{
				"_key": store.String("form-topic"), "blockType": store.String("select"), "name": store.String("topic"),
				"label": store.String("Topic"), "placeholder": store.String("Choose a topic"),
				"options": store.List(
					store.Object(store.Values{"_key": store.String("topic-support"), "label": store.String("Support"), "value": store.String("support")}),
					store.Object(store.Values{"_key": store.String("topic-sales"), "label": store.String("Sales"), "value": store.String("sales")}),
				),
			}),
			store.Object(store.Values{
				"_key": store.String("form-message"), "blockType": store.String("textarea"), "name": store.String("message"),
				"label": store.String("Message"), "required": store.Boolean(true),
			}),
			store.Object(store.Values{
				"_key": store.String("form-guidance"), "blockType": store.String("message"),
				"message": store.String("Attachments are optional. PNG images are accepted."),
			}),
			store.Object(store.Values{
				"_key": store.String("form-attachment"), "blockType": store.String("upload"), "name": store.String("attachment"),
				"label": store.String("Attachment"), "uploadCollection": store.String("media"), "maxFileSize": store.Number(1_048_576),
				"mimeTypes": store.List(store.Object(store.Values{"_key": store.String("form-attachment-png"), "mimeType": store.String("image/png")})),
			}),
			store.Object(store.Values{
				"_key": store.String("form-donation"), "blockType": store.String("payment"), "name": store.String("donation"),
				"label": store.String("Optional donation"), "basePrice": store.Number(25), "paymentProcessor": store.String("fixture"),
				"priceConditions": store.List(store.Object(store.Values{
					"_key": store.String("form-donation-sales"), "fieldToUse": store.String("topic"), "condition": store.String("equals"),
					"valueForCondition": store.String("sales"), "operator": store.String("add"), "valueType": store.String("static"),
					"valueForOperator": store.String("5"),
				})),
			}),
		),
		"emails": store.List(store.Object(store.Values{
			"_key": store.String("form-notification"), "emailTo": store.String("forms@riducms.test"),
			"emailFrom": store.String("website@riducms.test"), "replyTo": store.String("{{email}}"),
			"subject": store.String("New {{topic}} request"), "message": store.String("{{*:table}}"),
		})),
	}, ridu.MutationOptions{Actor: &editor, ActorCollection: "users"})
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed form: %w", err)
	}
	contactSubmission, err := application.Local().CreateWithOptions(ctx, "form-submissions", store.Values{
		"form": store.String(contactForm.ID),
		"submissionData": store.List(
			store.Object(store.Values{"_key": store.String("submission-name"), "field": store.String("name"), "value": store.String("Grace Hopper")}),
			store.Object(store.Values{"_key": store.String("submission-email"), "field": store.String("email"), "value": store.String("grace@example.test")}),
			store.Object(store.Values{"_key": store.String("submission-topic"), "field": store.String("topic"), "value": store.String("support")}),
			store.Object(store.Values{"_key": store.String("submission-message"), "field": store.String("message"), "value": store.String("Please send the Ridu migration guide.")}),
		),
	}, ridu.MutationOptions{Actor: &editor, ActorCollection: "users"})
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed form submission: %w", err)
	}
	settings, err := application.Local().UpdateGlobal(ctx, "site-settings", store.Values{
		"siteName":     store.String("  Ridu editorial kitchen sink  "),
		"announcement": store.String("Globals now use their own admin and API routes."),
		"navigation": store.List(store.Object(store.Values{
			"_key": store.String("global-nav-about"), "label": store.String("About"), "page": store.String(page.ID),
		})),
	}, 0, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed site settings: %w", err)
	}
	if _, err := application.Local().PublishGlobal(ctx, "site-settings", settings.Revision, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("publish site settings: %w", err)
	}
	publishedPost, err = application.Local().PublishChanges(ctx, "posts", publishedPost.ID, store.Values{
		"relatedContent": store.Object(store.Values{"relationTo": store.String("pages"), "id": store.String(page.ID)}),
	}, publishedPost.Revision, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("link polymorphic content: %w", err)
	}

	if _, err := application.Local().Create(ctx, "events", store.Values{
		"name": store.String("Ridu contributor workshop"), "startsAt": store.String("2026-09-15T09:30:00Z"),
		"endsAt": store.String("2026-09-15T16:30:00Z"), "capacity": store.Number(24), "online": store.Boolean(false),
		"venue": store.String("The contract test studio"), "contact": store.String("events@example.test"),
		"schedule": store.List(
			store.Object(store.Values{"_key": store.String("slot-intro"), "time": store.String("2026-09-15T09:30:00Z"), "title": store.String("Schema tour"), "speaker": store.String(editor.ID)}),
			store.Object(store.Values{"_key": store.String("slot-admin"), "time": store.String("2026-09-15T11:00:00Z"), "title": store.String("Admin gap audit"), "speaker": store.String(administrator.ID)}),
		),
		"registrationSettings": store.Object(store.Values{"waitlist": store.Boolean(true), "reminders": store.List(store.Number(7), store.Number(1))}),
	}, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed event: %w", err)
	}

	if _, err := application.Local().Create(ctx, "editorial-notes", store.Values{
		"title": store.String("Administrator-only launch notes"), "owner": store.String(administrator.ID),
		"note":                store.String("Editors can list this note but cannot see the protected details."),
		"confidentialDetails": store.String("Field-level read access removes this value from editor responses."),
	}, &administrator); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed admin note: %w", err)
	}
	if _, err := application.Local().Create(ctx, "editorial-notes", store.Values{
		"title": store.String("Contributor pitch"), "owner": store.String(contributor.ID),
		"note": store.String("The contributor account sees this note through an owner predicate."),
	}, &contributor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed contributor note: %w", err)
	}
	if _, err := application.Local().Create(ctx, "redirects", store.Values{
		"from": store.String("/old-about"), "to": store.String("/about"), "type": store.String("permanent"), "enabled": store.Boolean(true),
	}, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed redirect: %w", err)
	}
	if _, err := application.Local().Create(ctx, "payload-only-capabilities", store.Values{
		"title":               store.String("Field and array parity"),
		"code":                store.String("export const parity = true;"),
		"audiences":           store.List(store.String("editors"), store.String("reviewers")),
		"priority":            store.String("high"),
		"location":            store.List(store.Number(-0.1276), store.Number(51.5072)),
		"internalName":        store.String("field-array-showcase"),
		"implementationNotes": store.String("The collapsible is layout-only; these values remain top-level."),
		"team": store.List(
			store.Object(store.Values{"_key": store.String("team-rhea"), "displayName": store.String("Rhea"), "email": store.String("rhea@example.test"), "role": store.String("author")}),
			store.Object(store.Values{"_key": store.String("team-zeno"), "displayName": store.String("Zeno"), "email": store.String("zeno@example.test"), "role": store.String("reviewer")}),
		),
		"curriculumNodes": store.List(
			store.Object(store.Values{"_key": store.String("node-lesson"), "nodeType": store.String("lesson"), "lesson": store.String("lesson-intro"), "orderIndex": store.Number(10)}),
			store.Object(store.Values{"_key": store.String("node-question"), "nodeType": store.String("question"), "question": store.String("question-check"), "orderIndex": store.Number(20)}),
		),
		"questionParts": store.List(
			store.Object(store.Values{"_key": store.String("part-choice"), "blockType": store.String("choice"), "optionKey": store.String("A"), "label": store.String("Alpha")}),
			store.Object(store.Values{"_key": store.String("part-reorder"), "blockType": store.String("reorder"), "optionKey": store.String("B"), "label": store.String("Beta")}),
		),
	}, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed field showcase: %w", err)
	}

	editorialFolder, err := application.Local().Create(ctx, "folders", store.Values{
		"name": store.String("Editorial"),
	}, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("seed folder: %w", err)
	}
	if _, err := application.Local().Create(ctx, "folders", store.Values{
		"name": store.String("Archive"), "parent": store.String(editorialFolder.ID),
	}, &editor); err != nil {
		return fixtureSeed{}, fmt.Errorf("seed folder: %w", err)
	}
	draftPost, err = application.Local().Update(ctx, "posts", draftPost.ID, store.Values{
		"folder": store.String(editorialFolder.ID),
	}, &contributor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("organize draft post: %w", err)
	}
	publishedPost, err = application.Local().PublishChanges(ctx, "posts", publishedPost.ID, store.Values{
		"folder": store.String(editorialFolder.ID), "parent": store.String(draftPost.ID),
	}, publishedPost.Revision, &editor)
	if err != nil {
		return fixtureSeed{}, fmt.Errorf("organize published post: %w", err)
	}
	if _, err := createUser(ctx, application, &administrator, "users_api", store.Values{
		"name": store.String("API Integrator"), "email": store.String("api@riducms.test"),
		"role": store.String(roleAPIOnly),
	}, "ridu-api"); err != nil {
		return fixtureSeed{}, err
	}

	return fixtureSeed{
		Administrator: administrator,
		Editor:        editor,
		Contributor:   contributor,
		PublishedPost: publishedPost,
		DraftPost:     draftPost,
		Form:          contactForm,
		Submission:    contactSubmission,
	}, nil
}

func createUser(ctx context.Context, application *ridu.App, actor *store.Document, id string, values store.Values, password string) (store.Document, error) {
	user, err := application.Local().Import(ctx, "users", values, ridu.ImportOptions{ID: id, Status: store.StatusPublished}, actor)
	if err != nil {
		return store.Document{}, fmt.Errorf("create user: %w", err)
	}
	if err := application.SetPassword(ctx, "users", user.ID, password); err != nil {
		return store.Document{}, fmt.Errorf("set user password: %w", err)
	}
	return user, nil
}

func uploadFixtureImage(ctx context.Context, application *ridu.App, actor *store.Document, filename string, fill color.RGBA, values store.Values) (store.Document, error) {
	document, err := application.Upload(ctx, "media", ridu.UploadInput{
		Filename: filename,
		Reader:   bytes.NewReader(coloredPNG(fill)),
		Data:     values,
		Actor:    actor,
	})
	if err != nil {
		return store.Document{}, fmt.Errorf("upload %s: %w", filename, err)
	}
	return document, nil
}

func richDocument(text string) store.Value {
	return store.Object(store.Values{
		"version": store.Number(richtext.DocumentVersion),
		"root": store.Object(store.Values{
			"type": store.String("root"),
			"children": store.List(store.Object(store.Values{
				"type":     store.String("paragraph"),
				"children": store.List(store.Object(store.Values{"type": store.String("text"), "text": store.String(text)})),
			})),
		}),
	})
}

func coloredPNG(fill color.RGBA) []byte {
	canvas := image.NewRGBA(image.Rect(0, 0, 24, 16))
	for y := 0; y < canvas.Bounds().Dy(); y++ {
		for x := 0; x < canvas.Bounds().Dx(); x++ {
			canvas.SetRGBA(x, y, fill)
		}
	}
	var encoded bytes.Buffer
	if err := png.Encode(&encoded, canvas); err != nil {
		panic(err)
	}
	return encoded.Bytes()
}
