// Package content contains the compile-tested model used by the public Quickstart.
package content

import (
	"github.com/riducms/ridu"
	"github.com/riducms/ridu/field"
	"github.com/riducms/ridu/plugins/richtext"
)

// Config is the smallest complete application model behind the Quickstart examples.
func Config() ridu.Config {
	return ridu.Config{
		Name:        "Documentation Quickstart",
		Admin:       ridu.AdminConfig{User: "users"},
		Plugins:     []ridu.Plugin{richtext.New()},
		Collections: []ridu.Collection{Users, Posts},
	}
}

// Users is the authenticated admin collection generated by the starter template.
var Users = ridu.Collection{
	Slug: "users",
	Auth: true,
	Access: ridu.CollectionAccess{
		Admin:  authenticatedOnly,
		Read:   authenticatedOnly,
		Update: authenticatedOnly,
		Delete: authenticatedOnly,
	},
	Fields: []field.Definition{
		field.Email("email", field.Required(), field.Unique()),
	},
}

// Posts is the starter collection after the Quickstart adds its summary field.
var Posts = ridu.Collection{
	Slug: "posts",
	Access: ridu.CollectionAccess{
		Create: authenticatedOnly,
		Read:   authenticatedOnly,
		Update: authenticatedOnly,
		Delete: authenticatedOnly,
	},
	Fields: []field.Definition{
		field.Text("title", field.Required()),
		field.Textarea(
			"summary",
			field.MaxLength(240),
			field.Description("A short introduction used by post cards."),
		),
		field.Select(
			"status",
			field.OneOf("draft", "published"),
			field.Default("draft"),
		),
		field.Relationship("author", field.To("users")),
		richtext.Field("content"),
	},
}

func authenticatedOnly(ctx ridu.AccessContext) (ridu.AccessDecision, error) {
	if ctx.Actor == nil {
		return ridu.Deny(), nil
	}
	return ridu.Allow(), nil
}
