export type {
	EmbeddedSchemaFormScope,
	EmbeddedSchemaFormProps,
	EmbeddedSchemaHeaderProps,
	EmbeddedSchemaVariantScope,
	EmbeddedSchemaDraft,
	EmbeddedSchemaDraftEditorProps,
	FieldAuthoringHost,
	FieldDocument,
	FieldReferenceBrowserProps,
	FieldReferenceFilter,
} from "#lib/authoring.js";
export type {
	PluginFieldBinding,
	PluginFieldProps,
	PluginForm,
	RegisteredPluginField,
	PluginFieldRegistration,
} from "#lib/field.js";
export {
	defineRowLabelPlugin,
	type RowLabelComponentProps,
	type RowLabelPlugin,
	type RowLabelSnapshot,
	type RowLabelValue,
} from "#lib/row-label.js";
export type { FieldDocumentForm, FieldFormResource, FieldLiveValidation } from "#lib/form.js";
export {
	defineAdminMessages,
	getAdminI18n,
	setAdminI18n,
	validateAdminMessages,
	type AdminI18n,
	type DefineAdminMessagesInput,
	type PluginMessageCatalog,
	type PluginTranslationKey,
} from "#lib/i18n.js";
export {
	ADMIN_PLUGIN_API_VERSION,
	resolveAdminExtensions,
	assertAdminPluginPairs,
	type AdminPlugin,
	type AdminContributions,
	type AdminDashboardPanel,
	type AdminDashboardPanelProps,
	type AdminLoaderProps,
	type AdminViewComponent,
	withAdminLoader,
	type AdminExtensionProps,
	type AdminLoginComponent,
	type AdminLoginComponentProps,
	type AdminLoginExtensionHost,
	type AdminAccountComponent,
	type AdminAccountComponentProps,
	type AdminAccountExtensionHost,
	type AdminAccountSurface,
	type AdminNavigationComponent,
	type AdminNavigationComponentProps,
	type AdminNavigationPosition,
	type AdminLogoutButton,
	type AdminLogoutButtonProps,
	type AdminLogoutExtensionHost,
	type AdminCoreView,
	type AdminCoreViewHost,
	type AdminCoreViewProps,
	type AdminCoreViewSurface,
	type AdminBrandComponent,
	type AdminBrandComponentProps,
	type AdminBrandSurface,
	type AdminShellSlot,
	type AdminShellSlotProps,
	type AdminShellSlotPosition,
	type AdminProvider,
	type AdminProviderProps,
	type AdminDocumentAction,
	type AdminDocumentExtensionHost,
	type AdminDocumentExtensionProps,
	type AdminDocumentView,
	type AdminExtensionNotificationTone,
	type AdminListCellRenderer,
	type AdminListCellRendererProps,
	type AdminCollectionList,
	type AdminListResultsRenderer,
	type AdminListResultsRendererProps,
	type AdminRouteNavigation,
	type AdminPluginPair,
	type AdminRoute,
	type BackendAdminPlugin,
	type ResolvedAdminExtensions,
} from "#lib/plugin.js";

export { resolvePluginFields, type ResolvedPluginField } from "#lib/plugin-registry.js";
