/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
	| "Pacific/Midway"
	| "Pacific/Niue"
	| "Pacific/Honolulu"
	| "Pacific/Rarotonga"
	| "America/Anchorage"
	| "Pacific/Gambier"
	| "America/Los_Angeles"
	| "America/Tijuana"
	| "America/Denver"
	| "America/Phoenix"
	| "America/Chicago"
	| "America/Guatemala"
	| "America/New_York"
	| "America/Bogota"
	| "America/Caracas"
	| "America/Santiago"
	| "America/Buenos_Aires"
	| "America/Sao_Paulo"
	| "Atlantic/South_Georgia"
	| "Atlantic/Azores"
	| "Atlantic/Cape_Verde"
	| "Europe/London"
	| "Europe/Berlin"
	| "Africa/Lagos"
	| "Europe/Athens"
	| "Africa/Cairo"
	| "Europe/Moscow"
	| "Asia/Riyadh"
	| "Asia/Dubai"
	| "Asia/Baku"
	| "Asia/Karachi"
	| "Asia/Tashkent"
	| "Asia/Calcutta"
	| "Asia/Dhaka"
	| "Asia/Almaty"
	| "Asia/Jakarta"
	| "Asia/Bangkok"
	| "Asia/Shanghai"
	| "Asia/Singapore"
	| "Asia/Tokyo"
	| "Asia/Seoul"
	| "Australia/Brisbane"
	| "Australia/Sydney"
	| "Pacific/Guam"
	| "Pacific/Noumea"
	| "Pacific/Auckland"
	| "Pacific/Fiji";

export interface Config {
	auth: {
		users: UserAuthOperations;
	};
	blocks: {};
	collections: {
		users: User;
		media: Media;
		categories: Category;
		posts: Post;
		pages: Page;
		events: Event;
		"editorial-notes": EditorialNote;
		redirects: Redirect;
		"payload-capabilities": PayloadCapability;
		forms: Form;
		"form-submissions": FormSubmission;
		"payload-kv": PayloadKv;
		"payload-jobs": PayloadJob;
		"payload-locked-documents": PayloadLockedDocument;
		"payload-preferences": PayloadPreference;
		"payload-migrations": PayloadMigration;
	};
	collectionsJoins: {
		categories: {
			relatedPosts: "posts";
		};
	};
	collectionsSelect: {
		users: UsersSelect<false> | UsersSelect<true>;
		media: MediaSelect<false> | MediaSelect<true>;
		categories: CategoriesSelect<false> | CategoriesSelect<true>;
		posts: PostsSelect<false> | PostsSelect<true>;
		pages: PagesSelect<false> | PagesSelect<true>;
		events: EventsSelect<false> | EventsSelect<true>;
		"editorial-notes": EditorialNotesSelect<false> | EditorialNotesSelect<true>;
		redirects: RedirectsSelect<false> | RedirectsSelect<true>;
		"payload-capabilities": PayloadCapabilitiesSelect<false> | PayloadCapabilitiesSelect<true>;
		forms: FormsSelect<false> | FormsSelect<true>;
		"form-submissions": FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
		"payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
		"payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
		"payload-locked-documents":
			PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
		"payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
		"payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
	};
	db: {
		defaultIDType: number;
	};
	fallbackLocale: ("false" | "none" | "null") | false | null | ("en" | "es") | ("en" | "es")[];
	globals: {
		"site-settings": SiteSetting;
	};
	globalsSelect: {
		"site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>;
	};
	locale: "en" | "es";
	widgets: {
		collections: CollectionsWidget;
	};
	user: User;
	jobs: {
		tasks: {
			schedulePublish: TaskSchedulePublish;
			inline: {
				input: unknown;
				output: unknown;
			};
		};
		workflows: unknown;
	};
}
export interface UserAuthOperations {
	forgotPassword: {
		email: string;
		password: string;
	};
	login: {
		email: string;
		password: string;
	};
	registerFirstUser: {
		email: string;
		password: string;
	};
	unlock: {
		email: string;
		password: string;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: number;
	/**
	 * The name shown on authored content.
	 */
	name: string;
	role: "administrator" | "editor" | "contributor";
	contactEmail?: string | null;
	profile?: {
		/**
		 * Short biography displayed on author pages.
		 */
		bio?: string | null;
		location?: string | null;
		timezone?: string | null;
		availableForReview?: boolean | null;
	};
	/**
	 * Visible only to administrators.
	 */
	privateNotes?: string | null;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string | null;
	resetPasswordExpiration?: string | null;
	salt?: string | null;
	hash?: string | null;
	loginAttempts?: number | null;
	lockUntil?: string | null;
	sessions?:
		| {
				id: string;
				createdAt?: string | null;
				expiresAt: string;
		  }[]
		| null;
	password?: string | null;
	collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
	id: number;
	/**
	 * Describe the image for people who cannot see it.
	 */
	alt: string;
	caption?: string | null;
	credit?: (number | null) | User;
	kind?: ("image" | "illustration" | "screenshot") | null;
	tags?:
		| {
				label: string;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	thumbnailURL?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
	sizes?: {
		card?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
		thumbnail?: {
			url?: string | null;
			width?: number | null;
			height?: number | null;
			mimeType?: string | null;
			filesize?: number | null;
			filename?: string | null;
		};
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
	id: number;
	name: string;
	slug: string;
	seo?: {
		title?: string | null;
		canonicalURL?: string | null;
		description?: string | null;
		socialImage?: (number | null) | Media;
	};
	/**
	 * Payload can expose the inverse side of a relationship without storing IDs here.
	 */
	relatedPosts?: {
		docs?: (number | Post)[];
		hasNextPage?: boolean;
		totalDocs?: number;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
	id: number;
	title: string;
	slug?: string | null;
	summary: string;
	author?: (number | null) | User;
	category?: (number | null) | Category;
	status?: ("draft" | "published") | null;
	featured?: boolean | null;
	readingMinutes?: number | null;
	publishDate?: string | null;
	cover?: (number | null) | Media;
	gallery?: (number | Media)[] | null;
	content?: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ("ltr" | "rtl") | null;
			format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	} | null;
	collaborators?: (number | User)[] | null;
	relatedPosts?: (number | Post)[] | null;
	relatedContent?:
		| ({
				relationTo: "posts";
				value: number | Post;
		  } | null)
		| ({
				relationTo: "pages";
				value: number | Page;
		  } | null);
	seo?: {
		title?: string | null;
		canonicalURL?: string | null;
		description?: string | null;
		socialImage?: (number | null) | Media;
	};
	links?:
		| {
				label: string;
				url: string;
				newWindow?: boolean | null;
				id?: string | null;
		  }[]
		| null;
	layout?:
		| (
				| {
						tone?: ("note" | "warning" | "success") | null;
						body: string;
						id?: string | null;
						blockName?: string | null;
						blockType: "callout";
				  }
				| {
						quote: string;
						attribution?: string | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "quote";
				  }
				| {
						posts: (number | Post)[];
						id?: string | null;
						blockName?: string | null;
						blockType: "related-posts";
				  }
		  )[]
		| null;
	metadata?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	internalNotes?: string | null;
	lastEditedBy?: (number | null) | User;
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
	id: number;
	title: string;
	slug: string;
	template?: ("default" | "landing" | "legal") | null;
	layout: (
		| {
				heading: string;
				lede?: string | null;
				image?: (number | null) | Media;
				id?: string | null;
				blockName?: string | null;
				blockType: "hero";
		  }
		| {
				body: {
					root: {
						type: string;
						children: {
							type: any;
							version: number;
							[k: string]: unknown;
						}[];
						direction: ("ltr" | "rtl") | null;
						format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
						indent: number;
						version: number;
					};
					[k: string]: unknown;
				};
				id?: string | null;
				blockName?: string | null;
				blockType: "rich-text";
		  }
		| {
				post: number | Post;
				id?: string | null;
				blockName?: string | null;
				blockType: "featured-post";
		  }
	)[];
	navigation?: {
		label?: string | null;
		showInHeader?: boolean | null;
		showInFooter?: boolean | null;
	};
	meta?: {
		title?: string | null;
		description?: string | null;
		/**
		 * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
		 */
		image?: (number | null) | Media;
	};
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
	id: number;
	name: string;
	startsAt: string;
	endsAt?: string | null;
	capacity?: number | null;
	online?: boolean | null;
	venue?: string | null;
	meetingURL?: string | null;
	contact: string;
	schedule?:
		| {
				time: string;
				title: string;
				speaker?: (number | null) | User;
				id?: string | null;
		  }[]
		| null;
	registrationSettings?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-notes".
 */
export interface EditorialNote {
	id: number;
	title: string;
	owner: number | User;
	note: string;
	confidentialDetails?: string | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
	id: number;
	from: string;
	to: string;
	type?: ("permanent" | "temporary") | null;
	enabled?: boolean | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * A stable Payload field and collection reference used for side-by-side Ridu review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-capabilities".
 */
export interface PayloadCapability {
	id: number;
	title: string;
	/**
	 * Top-level fields can be placed in Payload's document sidebar.
	 */
	presentation?: ("article" | "gallery" | "video") | null;
	/**
	 * Complex field types can use the sidebar position too.
	 *
	 * @minItems 2
	 * @maxItems 2
	 */
	location?: [number, number] | null;
	sourceCode?: string | null;
	minimum?: number | null;
	boundedRows?:
		| {
				label: string;
				id?: string | null;
		  }[]
		| null;
	/**
	 * Virtual and read-only fields can share the sidebar with editable fields.
	 */
	computedLabel?: string | null;
	updatedAt: string;
	createdAt: string;
	deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
	id: number;
	title: string;
	fields?:
		| (
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						required?: boolean | null;
						defaultValue?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "checkbox";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "country";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "email";
				  }
				| {
						message?: {
							root: {
								type: string;
								children: {
									type: any;
									version: number;
									[k: string]: unknown;
								}[];
								direction: ("ltr" | "rtl") | null;
								format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
								indent: number;
								version: number;
							};
							[k: string]: unknown;
						} | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "message";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						defaultValue?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "number";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						placeholder?: string | null;
						options?:
							| {
									label: string;
									value: string;
									id?: string | null;
							  }[]
							| null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "select";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "state";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "text";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "textarea";
				  }
				| {
						name: string;
						label?: string | null;
						uploadCollection: "media";
						mimeTypes?:
							| {
									mimeType: string;
									id?: string | null;
							  }[]
							| null;
						width?: number | null;
						maxFileSize?: number | null;
						required?: boolean | null;
						multiple?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "upload";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						required?: boolean | null;
						defaultValue?: string | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "date";
				  }
				| {
						name: string;
						label?: string | null;
						width?: number | null;
						defaultValue?: string | null;
						options?:
							| {
									label: string;
									value: string;
									id?: string | null;
							  }[]
							| null;
						required?: boolean | null;
						id?: string | null;
						blockName?: string | null;
						blockType: "radio";
				  }
		  )[]
		| null;
	submitButtonLabel?: string | null;
	confirmationType?: ("message" | "redirect") | null;
	confirmationMessage?: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ("ltr" | "rtl") | null;
			format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	} | null;
	redirect?: {
		type?: ("reference" | "custom") | null;
		reference?: {
			relationTo: "pages";
			value: number | Page;
		} | null;
		url?: string | null;
	};
	emails?:
		| {
				emailTo?: string | null;
				cc?: string | null;
				bcc?: string | null;
				replyTo?: string | null;
				emailFrom?: string | null;
				subject: string;
				message?: {
					root: {
						type: string;
						children: {
							type: any;
							version: number;
							[k: string]: unknown;
						}[];
						direction: ("ltr" | "rtl") | null;
						format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
						indent: number;
						version: number;
					};
					[k: string]: unknown;
				} | null;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
	id: number;
	form: number | Form;
	submissionData?:
		| {
				field: string;
				value: string;
				id?: string | null;
		  }[]
		| null;
	submissionUploads?:
		| {
				field: string;
				value: {
					relationTo: "media";
					value: number | Media;
				}[];
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
	id: number;
	key: string;
	data:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
	id: number;
	/**
	 * Input data provided to the job
	 */
	input?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	taskStatus?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	completedAt?: string | null;
	totalTried?: number | null;
	/**
	 * If hasError is true this job will not be retried
	 */
	hasError?: boolean | null;
	/**
	 * If hasError is true, this is the error that caused it
	 */
	error?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	/**
	 * Task execution log
	 */
	log?:
		| {
				executedAt: string;
				completedAt: string;
				taskSlug: "inline" | "schedulePublish";
				taskID: string;
				input?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				output?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				state: "failed" | "succeeded";
				error?:
					| {
							[k: string]: unknown;
					  }
					| unknown[]
					| string
					| number
					| boolean
					| null;
				id?: string | null;
		  }[]
		| null;
	taskSlug?: ("inline" | "schedulePublish") | null;
	queue?: string | null;
	waitUntil?: string | null;
	processing?: boolean | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
	id: number;
	document?:
		| ({
				relationTo: "users";
				value: number | User;
		  } | null)
		| ({
				relationTo: "media";
				value: number | Media;
		  } | null)
		| ({
				relationTo: "categories";
				value: number | Category;
		  } | null)
		| ({
				relationTo: "posts";
				value: number | Post;
		  } | null)
		| ({
				relationTo: "pages";
				value: number | Page;
		  } | null)
		| ({
				relationTo: "events";
				value: number | Event;
		  } | null)
		| ({
				relationTo: "editorial-notes";
				value: number | EditorialNote;
		  } | null)
		| ({
				relationTo: "redirects";
				value: number | Redirect;
		  } | null)
		| ({
				relationTo: "payload-capabilities";
				value: number | PayloadCapability;
		  } | null)
		| ({
				relationTo: "forms";
				value: number | Form;
		  } | null)
		| ({
				relationTo: "form-submissions";
				value: number | FormSubmission;
		  } | null);
	globalSlug?: string | null;
	user: {
		relationTo: "users";
		value: number | User;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
	id: number;
	user: {
		relationTo: "users";
		value: number | User;
	};
	key?: string | null;
	value?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
	id: number;
	name?: string | null;
	batch?: number | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
	name?: T;
	role?: T;
	contactEmail?: T;
	profile?:
		| T
		| {
				bio?: T;
				location?: T;
				timezone?: T;
				availableForReview?: T;
		  };
	privateNotes?: T;
	updatedAt?: T;
	createdAt?: T;
	email?: T;
	resetPasswordToken?: T;
	resetPasswordExpiration?: T;
	salt?: T;
	hash?: T;
	loginAttempts?: T;
	lockUntil?: T;
	sessions?:
		| T
		| {
				id?: T;
				createdAt?: T;
				expiresAt?: T;
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
	alt?: T;
	caption?: T;
	credit?: T;
	kind?: T;
	tags?:
		| T
		| {
				label?: T;
				id?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
	url?: T;
	thumbnailURL?: T;
	filename?: T;
	mimeType?: T;
	filesize?: T;
	width?: T;
	height?: T;
	focalX?: T;
	focalY?: T;
	sizes?:
		| T
		| {
				card?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
				thumbnail?:
					| T
					| {
							url?: T;
							width?: T;
							height?: T;
							mimeType?: T;
							filesize?: T;
							filename?: T;
					  };
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
	name?: T;
	slug?: T;
	seo?:
		| T
		| {
				title?: T;
				canonicalURL?: T;
				description?: T;
				socialImage?: T;
		  };
	relatedPosts?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
	title?: T;
	slug?: T;
	summary?: T;
	author?: T;
	category?: T;
	status?: T;
	featured?: T;
	readingMinutes?: T;
	publishDate?: T;
	cover?: T;
	gallery?: T;
	content?: T;
	collaborators?: T;
	relatedPosts?: T;
	relatedContent?: T;
	seo?:
		| T
		| {
				title?: T;
				canonicalURL?: T;
				description?: T;
				socialImage?: T;
		  };
	links?:
		| T
		| {
				label?: T;
				url?: T;
				newWindow?: T;
				id?: T;
		  };
	layout?:
		| T
		| {
				callout?:
					| T
					| {
							tone?: T;
							body?: T;
							id?: T;
							blockName?: T;
					  };
				quote?:
					| T
					| {
							quote?: T;
							attribution?: T;
							id?: T;
							blockName?: T;
					  };
				"related-posts"?:
					| T
					| {
							posts?: T;
							id?: T;
							blockName?: T;
					  };
		  };
	metadata?: T;
	internalNotes?: T;
	lastEditedBy?: T;
	updatedAt?: T;
	createdAt?: T;
	_status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
	title?: T;
	slug?: T;
	template?: T;
	layout?:
		| T
		| {
				hero?:
					| T
					| {
							heading?: T;
							lede?: T;
							image?: T;
							id?: T;
							blockName?: T;
					  };
				"rich-text"?:
					| T
					| {
							body?: T;
							id?: T;
							blockName?: T;
					  };
				"featured-post"?:
					| T
					| {
							post?: T;
							id?: T;
							blockName?: T;
					  };
		  };
	navigation?:
		| T
		| {
				label?: T;
				showInHeader?: T;
				showInFooter?: T;
		  };
	meta?:
		| T
		| {
				title?: T;
				description?: T;
				image?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
	_status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
	name?: T;
	startsAt?: T;
	endsAt?: T;
	capacity?: T;
	online?: T;
	venue?: T;
	meetingURL?: T;
	contact?: T;
	schedule?:
		| T
		| {
				time?: T;
				title?: T;
				speaker?: T;
				id?: T;
		  };
	registrationSettings?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-notes_select".
 */
export interface EditorialNotesSelect<T extends boolean = true> {
	title?: T;
	owner?: T;
	note?: T;
	confidentialDetails?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
	from?: T;
	to?: T;
	type?: T;
	enabled?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-capabilities_select".
 */
export interface PayloadCapabilitiesSelect<T extends boolean = true> {
	title?: T;
	presentation?: T;
	location?: T;
	sourceCode?: T;
	minimum?: T;
	boundedRows?:
		| T
		| {
				label?: T;
				id?: T;
		  };
	computedLabel?: T;
	updatedAt?: T;
	createdAt?: T;
	deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
	title?: T;
	fields?:
		| T
		| {
				checkbox?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							required?: T;
							defaultValue?: T;
							id?: T;
							blockName?: T;
					  };
				country?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				email?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				message?:
					| T
					| {
							message?: T;
							id?: T;
							blockName?: T;
					  };
				number?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				select?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							defaultValue?: T;
							placeholder?: T;
							options?:
								| T
								| {
										label?: T;
										value?: T;
										id?: T;
								  };
							required?: T;
							id?: T;
							blockName?: T;
					  };
				state?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				text?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				textarea?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							defaultValue?: T;
							required?: T;
							id?: T;
							blockName?: T;
					  };
				upload?:
					| T
					| {
							name?: T;
							label?: T;
							uploadCollection?: T;
							mimeTypes?:
								| T
								| {
										mimeType?: T;
										id?: T;
								  };
							width?: T;
							maxFileSize?: T;
							required?: T;
							multiple?: T;
							id?: T;
							blockName?: T;
					  };
				date?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							required?: T;
							defaultValue?: T;
							id?: T;
							blockName?: T;
					  };
				radio?:
					| T
					| {
							name?: T;
							label?: T;
							width?: T;
							defaultValue?: T;
							options?:
								| T
								| {
										label?: T;
										value?: T;
										id?: T;
								  };
							required?: T;
							id?: T;
							blockName?: T;
					  };
		  };
	submitButtonLabel?: T;
	confirmationType?: T;
	confirmationMessage?: T;
	redirect?:
		| T
		| {
				type?: T;
				reference?: T;
				url?: T;
		  };
	emails?:
		| T
		| {
				emailTo?: T;
				cc?: T;
				bcc?: T;
				replyTo?: T;
				emailFrom?: T;
				subject?: T;
				message?: T;
				id?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
	form?: T;
	submissionData?:
		| T
		| {
				field?: T;
				value?: T;
				id?: T;
		  };
	submissionUploads?:
		| T
		| {
				field?: T;
				value?: T;
				id?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
	key?: T;
	data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
	input?: T;
	taskStatus?: T;
	completedAt?: T;
	totalTried?: T;
	hasError?: T;
	error?: T;
	log?:
		| T
		| {
				executedAt?: T;
				completedAt?: T;
				taskSlug?: T;
				taskID?: T;
				input?: T;
				output?: T;
				state?: T;
				error?: T;
				id?: T;
		  };
	taskSlug?: T;
	queue?: T;
	waitUntil?: T;
	processing?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
	document?: T;
	globalSlug?: T;
	user?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
	user?: T;
	key?: T;
	value?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
	name?: T;
	batch?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
	id: number;
	siteName: string;
	announcement?: string | null;
	navigation?:
		| {
				label: string;
				page: number | Page;
				id?: string | null;
		  }[]
		| null;
	meta?: {
		title?: string | null;
		description?: string | null;
		/**
		 * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
		 */
		image?: (number | null) | Media;
	};
	_status?: ("draft" | "published") | null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
	siteName?: T;
	announcement?: T;
	navigation?:
		| T
		| {
				label?: T;
				page?: T;
				id?: T;
		  };
	meta?:
		| T
		| {
				title?: T;
				description?: T;
				image?: T;
		  };
	_status?: T;
	updatedAt?: T;
	createdAt?: T;
	globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
	data?: {
		[k: string]: unknown;
	};
	width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
	input: {
		type?: ("publish" | "unpublish") | null;
		locale?: string | null;
		doc?: {
			relationTo: "posts";
			value: number | Post;
		} | null;
		global?: string | null;
		user?: (number | null) | User;
	};
	output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
	[k: string]: unknown;
}

declare module "payload" {
	export interface GeneratedTypes extends Config {}
}
