package generate

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strings"
	"unicode"

	"github.com/riducms/ridu/internal/blocktypes"
	"github.com/riducms/ridu/schema"
)

type goModelMode int

const (
	goOutput goModelMode = iota
	goCreate
	goUpdate
	goAllLocales
	goAllLocalesValue
)

func goClient(manifest schema.Manifest) ([]byte, error) {
	snapshot := manifest.Snapshot()
	collections := snapshot.Collections
	catalog, err := blocktypes.Build(snapshot)
	if err != nil {
		return nil, err
	}
	blocks, err := newGoBlocks(catalog, snapshot)
	if err != nil {
		return nil, err
	}
	pluginTypes, pluginImports, _ := goPluginTypes(snapshot)
	var output strings.Builder
	output.WriteString("// Code generated by Ridu. DO NOT EDIT.\n")
	output.WriteString("package generated\n\n")
	output.WriteString("import (\n")
	output.WriteString("\t\"encoding/json\"\n\t\"fmt\"\n\t\"bytes\"\n\t\"strings\"\n\t\"errors\"\n\t\"sort\"\n\t\"encoding\"\n")
	output.WriteString("\t\"github.com/riducms/ridu/core\"\n")
	packages := make([]string, 0, len(pluginImports))
	for packagePath := range pluginImports {
		packages = append(packages, packagePath)
	}
	sort.Strings(packages)
	for _, packagePath := range packages {
		fmt.Fprintf(&output, "\t%s %q\n", pluginImports[packagePath], packagePath)
	}
	output.WriteString(")\n\n")
	usedNames := make(map[string]int)
	for _, collection := range collections {
		baseName := exportedGoIdentifier(collection.Labels.Singular)
		if baseName == "" {
			baseName = exportedGoIdentifier(string(collection.Slug))
		}
		usedNames[baseName]++
		if usedNames[baseName] > 1 {
			baseName += fmt.Sprint(usedNames[baseName])
		}
		fieldNames := goModelFieldNames(collection, "UnmarshalJSON")
		writeGoModel(&output, baseName, collection, goOutput, pluginTypes, fieldNames, blocks)
		writeGoModel(&output, baseName+"Create", collection, goCreate, pluginTypes, fieldNames, blocks)
		writeGoModel(&output, baseName+"Update", collection, goUpdate, pluginTypes, fieldNames, blocks)
		if blocks.localized {
			writeGoModel(&output, baseName+"AllLocales", collection, goAllLocales, pluginTypes, fieldNames, blocks)
		}
		variable := exportedGoIdentifier(collection.Labels.Plural)
		if variable == "" {
			variable = exportedGoIdentifier(string(collection.Slug))
		}
		variable += "Collection"
		fmt.Fprintf(&output, "var %s = core.NewTypedCollection[%s, %sCreate, %sUpdate](%q)\n\n", variable, baseName, baseName, baseName, collection.Slug)
		if blocks.localized {
			fmt.Fprintf(&output, "// %sAllLocales reads all translations with optional population and projection.\nvar %sAllLocales = core.NewTypedAllLocalesCollection[%sAllLocales](%q)\n\n", variable, variable, baseName, collection.Slug)
		}
	}
	for _, global := range snapshot.Globals {
		baseName := exportedGoIdentifier(global.Labels.Singular)
		if baseName == "" {
			baseName = exportedGoIdentifier(string(global.Slug))
		}
		usedNames[baseName]++
		if usedNames[baseName] > 1 {
			baseName += fmt.Sprint(usedNames[baseName])
		}
		fieldNames := goModelFieldNames(global, "UnmarshalJSON")
		writeGoModel(&output, baseName, global, goOutput, pluginTypes, fieldNames, blocks)
		writeGoModel(&output, baseName+"Update", global, goUpdate, pluginTypes, fieldNames, blocks)
		if blocks.localized {
			writeGoModel(&output, baseName+"AllLocales", global, goAllLocales, pluginTypes, fieldNames, blocks)
		}
		variable := exportedGoIdentifier(global.Labels.Singular)
		if variable == "" {
			variable = exportedGoIdentifier(string(global.Slug))
		}
		variable += "Global"
		fmt.Fprintf(&output, "var %s = core.NewTypedGlobal[%s, %sUpdate](%q)\n\n", variable, baseName, baseName, global.Slug)
		if blocks.localized {
			fmt.Fprintf(&output, "// %sAllLocales reads all translations with optional population and projection.\nvar %sAllLocales = core.NewTypedAllLocalesGlobal[%sAllLocales](%q)\n\n", variable, variable, baseName, global.Slug)
		}
	}
	blocks.write(&output, pluginTypes)
	blocks.writeSelects(&output)
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go client: %w\n%s", err, output.String())
	}
	if err := validateGoGeneratedSymbols(formatted); err != nil {
		return nil, err
	}
	return formatted, nil
}

func writeGoModel(output *strings.Builder, name string, collection schema.Collection, mode goModelMode, pluginTypes map[string]string, fieldNames []string, blocks *goBlocks) {
	switch mode {
	case goCreate:
		fmt.Fprintf(output, "// %s supplies a new document. Required values are concrete; defaulted values may be omitted, and nullable values use core.Set or core.Null.\n", name)
	case goUpdate:
		fmt.Fprintf(output, "// %s edits a document. Nil fields are unchanged; supplied block lists replace order and membership.\n", name)
	case goAllLocales:
		fmt.Fprintf(output, "// %s is an all-locales read: localized fields contain locale-code maps.\n", name)
	default:
		fmt.Fprintf(output, "// %s is a single-locale read. Authored fields can be omitted by access rules or projection.\n", name)
	}
	fmt.Fprintf(output, "type %s struct {\n", name)
	if goOutputMode(mode) {
		output.WriteString("\tID string `json:\"id\"`\n")
		output.WriteString("\tCreatedAt string `json:\"createdAt\"`\n")
		output.WriteString("\tUpdatedAt string `json:\"updatedAt\"`\n")
		if collection.Capabilities.Trash {
			output.WriteString("\tDeletedAt *string `json:\"deletedAt,omitempty\"`\n")
		}
		if collection.Capabilities.Versions {
			output.WriteString("\tStatus string `json:\"_status\"`\n")
			output.WriteString("\tRevision int `json:\"_revision\"`\n")
		}
	}
	for index, field := range collection.Fields {
		if !goFieldAppearsInMode(field, mode) {
			continue
		}
		// readOnly is an admin presentation hint, not an API authorization rule.
		// Framework-owned upload metadata is the one non-presentation vocabulary
		// that ordinary create/update inputs must not expose.
		if !goOutputMode(mode) && field.Category == schema.FieldCategoryUpload && field.Upload == nil {
			continue
		}
		fieldName := fieldNames[index]
		fieldType := blocks.fieldType(field, mode, pluginTypes, false)
		// Reads may omit every authored field through field-level access or an
		// explicit projection. Output models therefore preserve field presence
		// independently of authoring requiredness.
		optional := goOutputMode(mode) || mode == goUpdate || !generatedInputRequired(field) || mode == goCreate && generatedFieldHasDefault(field)
		fieldType = blocks.presence(field, fieldType, mode, optional)
		tag := field.Name
		if optional || mode == goUpdate {
			tag += goOmissionTag(field, mode)
		}
		writeGoFieldDoc(output, fieldName, field, fieldType, mode)
		fmt.Fprintf(output, "\t%s %s `json:%q`\n", fieldName, fieldType, tag)
	}
	output.WriteString("}\n\n")
	blocks.writeModelDecoder(output, name, collection, mode, pluginTypes, fieldNames)
}

func goModelFieldNames(collection schema.Collection, reserved ...string) []string {
	natural := make(map[string]bool, len(collection.Fields))
	for _, field := range collection.Fields {
		if goFieldAppearsInModel(field) {
			natural[exportedGoIdentifier(field.Name)] = true
		}
	}
	used := map[string]bool{
		"ID":        true,
		"CreatedAt": true,
		"UpdatedAt": true,
	}
	for _, name := range reserved {
		used[name] = true
	}
	if collection.Capabilities.Trash {
		used["DeletedAt"] = true
	}
	if collection.Capabilities.Versions {
		used["Status"] = true
		used["Revision"] = true
	}

	result := make([]string, len(collection.Fields))
	for index, field := range collection.Fields {
		if !goFieldAppearsInModel(field) {
			continue
		}
		base := exportedGoIdentifier(field.Name)
		name := base
		if used[name] {
			name = base + "Field"
			for suffix := 2; used[name] || natural[name]; suffix++ {
				name = base + "Field" + fmt.Sprint(suffix)
			}
		}
		used[name] = true
		result[index] = name
	}
	return result
}

func goFieldAppearsInModel(field schema.Field) bool {
	return field.Category != schema.FieldCategoryPresentation || field.Type == schema.FieldTypeJoin || field.Type == schema.FieldTypeVirtual
}

func goFieldType(field schema.Field, mode goModelMode, pluginTypes map[string]string) string {
	switch field.Type {
	case schema.FieldTypeText, schema.FieldTypeCode, schema.FieldTypeTextarea, schema.FieldTypeEmail, schema.FieldTypeDate, schema.FieldTypeRadio:
		return "string"
	case schema.FieldTypeSelect:
		if field.Select != nil && field.Select.HasMany {
			return "[]string"
		}
		return "string"
	case schema.FieldTypePoint:
		return "[2]float64"
	case schema.FieldTypeNumber:
		return "float64"
	case schema.FieldTypeTextList:
		return "[]string"
	case schema.FieldTypeNumberList:
		return "[]float64"
	case schema.FieldTypeCheckbox:
		return "bool"
	case schema.FieldTypeVirtual:
		if field.Virtual == nil {
			return "any"
		}
		switch field.Virtual.ValueType {
		case schema.ValueTypeString:
			return "string"
		case schema.ValueTypeNumber:
			return "float64"
		case schema.ValueTypeBoolean:
			return "bool"
		default:
			return "any"
		}
	case schema.FieldTypeJoin:
		return "[]map[string]any"
	case schema.FieldTypeRelationship:
		if field.Relationship != nil && field.Relationship.HasMany {
			return "[]string"
		}
		if field.Relationship != nil && field.Relationship.Polymorphic {
			return "map[string]any"
		}
		return "string"
	case schema.FieldTypeUpload:
		if field.Upload != nil && field.Upload.HasMany {
			return "[]string"
		}
		return "string"
	case schema.FieldTypeGroup:
		if field.Nested == nil {
			return "map[string]any"
		}
		return goAnonymousStruct(field.Nested.ResolvedFields(), mode, pluginTypes)
	case schema.FieldTypeArray:
		if field.Nested == nil {
			return "[]map[string]any"
		}
		return "[]" + goAnonymousStruct(field.Nested.ResolvedFields(), mode, pluginTypes)
	case schema.FieldTypeBlocks:
		panic("Blocks must be resolved through the block type catalog")
	case schema.FieldTypePlugin:
		if field.Plugin != nil {
			if typeName, exists := pluginTypes[field.Plugin.Key]; exists {
				return typeName
			}
		}
		return "json.RawMessage"
	default:
		return "any"
	}
}

func goAnonymousStruct(fields []schema.Field, mode goModelMode, pluginTypes map[string]string) string {
	var output strings.Builder
	output.WriteString("struct { ")
	for _, field := range fields {
		if field.Category == schema.FieldCategoryPresentation {
			continue
		}
		fieldType := goFieldType(field, mode, pluginTypes)
		// Nested output fields can be redacted or projected independently too.
		optional := goOutputMode(mode) || mode == goUpdate || !generatedInputRequired(field) || mode == goCreate && generatedFieldHasDefault(field)
		fieldType = goPresenceType(field, fieldType, mode, optional)
		tag := field.Name
		if optional {
			tag += goOmissionTag(field, mode)
		}
		fmt.Fprintf(&output, "%s %s `json:%q`; ", exportedGoIdentifier(field.Name), fieldType, tag)
	}
	output.WriteString("}")
	return output.String()
}

func goPresenceType(field schema.Field, fieldType string, mode goModelMode, optional bool) string {
	nullable := !field.Required
	if !goOutputMode(mode) {
		nullable = !generatedInputRequired(field)
	}
	// A plugin-owned named Go type can have a nil-able underlying type or a
	// custom marshaler that emits null. The manifest intentionally does not
	// expose executable type internals, so mutation generation must treat every
	// exact plugin input type as unproven rather than guessing from its name.
	nonNullInput := !goOutputMode(mode) && !nullable && (field.Type == schema.FieldTypePlugin || goTypeCanEncodeNull(fieldType))
	if !optional {
		if nonNullInput {
			return "core.NonNullInput[" + fieldType + "]"
		}
		return fieldType
	}
	if mode == goCreate || mode == goUpdate {
		if nullable {
			return "*core.Input[" + fieldType + "]"
		}
		if nonNullInput {
			return "*core.NonNullInput[" + fieldType + "]"
		}
		return "*" + fieldType
	}
	if !strings.HasPrefix(fieldType, "*") && !strings.HasPrefix(fieldType, "[]") && fieldType != "any" {
		return "*" + fieldType
	}
	return fieldType
}

func goTypeCanEncodeNull(fieldType string) bool {
	return fieldType == "any" ||
		fieldType == "json.RawMessage" ||
		strings.HasPrefix(fieldType, "[]") ||
		strings.HasPrefix(fieldType, "map[") ||
		strings.HasPrefix(fieldType, "interface{")
}

func generatedFieldHasDefault(field schema.Field) bool {
	return field.Default != nil || field.DynamicDefault ||
		field.Select != nil && field.Select.HasMany && len(field.Select.DefaultValues) != 0 ||
		field.Text != nil && field.Text.Slug != nil
}

func goPluginTypes(snapshot schema.Snapshot) (map[string]string, map[string]string, bool) {
	available := make(map[string]schema.PluginFieldType)
	for _, plugin := range snapshot.Plugins {
		for _, fieldType := range plugin.FieldTypes {
			if fieldType.GoPackage != "" && fieldType.GoType != "" {
				available[fieldType.Key] = fieldType
			}
		}
	}
	used := make(map[string]bool)
	needsJSON := false
	var inspect func([]schema.Field)
	inspect = func(fields []schema.Field) {
		for _, field := range fields {
			if field.Type == schema.FieldTypePlugin {
				if field.Plugin == nil || available[field.Plugin.Key].Key == "" {
					needsJSON = true
				} else {
					used[field.Plugin.Key] = true
				}
			}
			inspect(schema.ChildFields(field))
		}
	}
	for _, collection := range snapshot.Collections {
		inspect(collection.Fields)
	}
	for _, global := range snapshot.Globals {
		inspect(global.Fields)
	}

	result := make(map[string]string)
	imports := make(map[string]string)
	usedAliases := map[string]int{"core": 1, "json": 1, "fmt": 1, "bytes": 1, "strings": 1, "errors": 1, "sort": 1, "encoding": 1}
	for _, plugin := range snapshot.Plugins {
		for _, fieldType := range plugin.FieldTypes {
			if !used[fieldType.Key] || fieldType.GoPackage == "" || fieldType.GoType == "" {
				continue
			}
			alias, exists := imports[fieldType.GoPackage]
			if !exists {
				parts := strings.Split(fieldType.GoPackage, "/")
				base := strings.ToLower(exportedGoIdentifier(parts[len(parts)-1]))
				if base == "" {
					base = "plugin"
				}
				alias = base
				usedAliases[base]++
				if usedAliases[base] > 1 {
					alias += fmt.Sprint(usedAliases[base])
				}
				imports[fieldType.GoPackage] = alias
			}
			result[fieldType.Key] = alias + "." + fieldType.GoType
		}
	}
	return result, imports, needsJSON
}

// Initialisms follow ordinary Go naming while JSON tags retain authored field names.
var goInitialisms = map[string]bool{
	"ACL": true, "API": true, "ASCII": true, "CPU": true, "CSS": true, "DNS": true,
	"EOF": true, "GUID": true, "HTML": true, "HTTP": true, "HTTPS": true, "ID": true,
	"IP": true, "JSON": true, "QPS": true, "RAM": true, "RPC": true, "SLA": true,
	"SMTP": true, "SQL": true, "SSH": true, "TCP": true, "TLS": true, "TTL": true,
	"UDP": true, "UI": true, "UID": true, "UUID": true, "URI": true, "URL": true,
	"UTF8": true, "VM": true, "XML": true, "XSRF": true, "XSS": true,
}

func exportedGoIdentifier(value string) string {
	var words []string
	var current []rune
	flush := func() {
		if len(current) != 0 {
			words = append(words, string(current))
			current = nil
		}
	}
	runes := []rune(value)
	for index, character := range runes {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			flush()
			continue
		}
		if len(current) > 0 && unicode.IsUpper(character) {
			previous := runes[index-1]
			nextLower := index+1 < len(runes) && unicode.IsLower(runes[index+1])
			if unicode.IsLower(previous) || unicode.IsDigit(previous) || unicode.IsUpper(previous) && nextLower {
				flush()
			}
		}
		current = append(current, character)
	}
	flush()
	for index, word := range words {
		upper := strings.ToUpper(word)
		if goInitialisms[upper] {
			words[index] = upper
			continue
		}
		runes := []rune(strings.ToLower(word))
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		words[index] = string(runes)
	}
	result := strings.Join(words, "")
	if result != "" && unicode.IsDigit([]rune(result)[0]) {
		result = "Value" + result
	}
	keywords := []string{"Break", "Default", "Func", "Interface", "Select", "Case", "Defer", "Go", "Map", "Struct", "Chan", "Else", "Goto", "Package", "Switch", "Const", "Fallthrough", "If", "Range", "Type", "Continue", "For", "Import", "Return", "Var"}
	sort.Strings(keywords)
	if index := sort.SearchStrings(keywords, result); index < len(keywords) && keywords[index] == result {
		result += "Value"
	}
	return result
}

func validateGoGeneratedSymbols(source []byte) error {
	file, err := parser.ParseFile(token.NewFileSet(), "ridu.generated.go", source, 0)
	if err != nil {
		return err
	}
	used := map[string]bool{}
	var issues []schema.Issue
	reserve := func(name string) {
		if used[name] {
			issues = append(issues, schema.Issue{Code: "block_type_name_conflict", Path: "generated.go." + name, Message: "generated Go symbol collides with another model, block, relationship, or select declaration; choose distinct field names, select values, or block type names"})
		}
		used[name] = true
	}
	for _, decl := range file.Decls {
		switch decl := decl.(type) {
		case *ast.GenDecl:
			for _, spec := range decl.Specs {
				switch spec := spec.(type) {
				case *ast.TypeSpec:
					reserve(spec.Name.Name)
				case *ast.ValueSpec:
					for _, name := range spec.Names {
						reserve(name.Name)
					}
				}
			}
		case *ast.FuncDecl:
			if decl.Recv == nil {
				reserve(decl.Name.Name)
			}
		}
	}
	if len(issues) != 0 {
		return schema.NewValidationError(issues)
	}
	return nil
}

// Positive primitive-list counts also require a submitted, non-null container.
// Read hooks retain logical types but do not rerun these write constraints.
func generatedInputRequired(field schema.Field) bool {
	return field.Required || ((field.Type == schema.FieldTypeTextList || field.Type == schema.FieldTypeNumberList) && field.List != nil && field.List.MinRows > 0)
}

func goOmissionTag(field schema.Field, mode goModelMode) string {
	if goOutputMode(mode) && (field.Type == schema.FieldTypeTextList || field.Type == schema.FieldTypeNumberList) {
		return ",omitzero"
	}
	return ",omitempty"
}
