package generate

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/riducms/ridu/schema"
)

type goModelMode int

const (
	goOutput goModelMode = iota
	goCreate
	goUpdate
)

func goClient(manifest schema.Manifest) ([]byte, error) {
	snapshot := manifest.Snapshot()
	collections := snapshot.Collections
	pluginTypes, pluginImports, needsJSON := goPluginTypes(snapshot)
	var output strings.Builder
	output.WriteString("// Code generated by Ridu. DO NOT EDIT.\n")
	output.WriteString("package generated\n\n")
	output.WriteString("import (\n")
	if needsJSON {
		output.WriteString("\t\"encoding/json\"\n")
	}
	output.WriteString("\t\"github.com/riducms/ridu/core\"\n")
	packages := make([]string, 0, len(pluginImports))
	for packagePath := range pluginImports {
		packages = append(packages, packagePath)
	}
	sort.Strings(packages)
	for _, packagePath := range packages {
		fmt.Fprintf(&output, "\t%s %q\n", pluginImports[packagePath], packagePath)
	}
	output.WriteString(")\n\n")
	usedNames := make(map[string]int)
	for _, collection := range collections {
		baseName := exportedGoIdentifier(collection.Labels.Singular)
		if baseName == "" {
			baseName = exportedGoIdentifier(string(collection.Slug))
		}
		usedNames[baseName]++
		if usedNames[baseName] > 1 {
			baseName += fmt.Sprint(usedNames[baseName])
		}
		fieldNames := goModelFieldNames(collection)
		writeGoModel(&output, baseName, collection, goOutput, pluginTypes, fieldNames)
		writeGoModel(&output, baseName+"Create", collection, goCreate, pluginTypes, fieldNames)
		writeGoModel(&output, baseName+"Update", collection, goUpdate, pluginTypes, fieldNames)
		variable := exportedGoIdentifier(collection.Labels.Plural)
		if variable == "" {
			variable = exportedGoIdentifier(string(collection.Slug))
		}
		variable += "Collection"
		fmt.Fprintf(&output, "var %s = core.NewTypedCollection[%s, %sCreate, %sUpdate](%q)\n\n", variable, baseName, baseName, baseName, collection.Slug)
	}
	for _, global := range snapshot.Globals {
		baseName := exportedGoIdentifier(global.Labels.Singular)
		if baseName == "" {
			baseName = exportedGoIdentifier(string(global.Slug))
		}
		usedNames[baseName]++
		if usedNames[baseName] > 1 {
			baseName += fmt.Sprint(usedNames[baseName])
		}
		fieldNames := goModelFieldNames(global)
		writeGoModel(&output, baseName, global, goOutput, pluginTypes, fieldNames)
		writeGoModel(&output, baseName+"Update", global, goUpdate, pluginTypes, fieldNames)
		variable := exportedGoIdentifier(global.Labels.Singular)
		if variable == "" {
			variable = exportedGoIdentifier(string(global.Slug))
		}
		variable += "Global"
		fmt.Fprintf(&output, "var %s = core.NewTypedGlobal[%s, %sUpdate](%q)\n\n", variable, baseName, baseName, global.Slug)
	}
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go client: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func writeGoModel(output *strings.Builder, name string, collection schema.Collection, mode goModelMode, pluginTypes map[string]string, fieldNames []string) {
	fmt.Fprintf(output, "type %s struct {\n", name)
	if mode == goOutput {
		output.WriteString("\tID string `json:\"id\"`\n")
		output.WriteString("\tCreatedAt string `json:\"createdAt\"`\n")
		output.WriteString("\tUpdatedAt string `json:\"updatedAt\"`\n")
		if collection.Capabilities.Trash {
			output.WriteString("\tDeletedAt *string `json:\"deletedAt,omitempty\"`\n")
		}
		if collection.Capabilities.Versions {
			output.WriteString("\tStatus string `json:\"_status\"`\n")
			output.WriteString("\tRevision int `json:\"_revision\"`\n")
		}
	}
	for index, field := range collection.Fields {
		if field.Category == schema.FieldCategoryPresentation && (mode != goOutput || field.Type != schema.FieldTypeJoin && field.Type != schema.FieldTypeVirtual) {
			continue
		}
		// readOnly is an admin presentation hint, not an API authorization rule.
		// Framework-owned upload metadata is the one non-presentation vocabulary
		// that ordinary create/update inputs must not expose.
		if mode != goOutput && field.Category == schema.FieldCategoryUpload && field.Upload == nil {
			continue
		}
		fieldName := fieldNames[index]
		fieldType := goFieldType(field, mode, pluginTypes)
		// Reads may omit every authored field through field-level access or an
		// explicit projection. Output models therefore preserve field presence
		// independently of authoring requiredness.
		optional := mode == goOutput || mode == goUpdate || !field.Required || mode == goCreate && generatedFieldHasDefault(field)
		fieldType = goPresenceType(field, fieldType, mode, optional)
		tag := field.Name
		if optional || mode == goUpdate {
			tag += ",omitempty"
		}
		fmt.Fprintf(output, "\t%s %s `json:%q`\n", fieldName, fieldType, tag)
	}
	output.WriteString("}\n\n")
}

func goModelFieldNames(collection schema.Collection) []string {
	natural := make(map[string]bool, len(collection.Fields))
	for _, field := range collection.Fields {
		if goFieldAppearsInModel(field) {
			natural[exportedGoIdentifier(field.Name)] = true
		}
	}
	used := map[string]bool{
		"ID":        true,
		"CreatedAt": true,
		"UpdatedAt": true,
	}
	if collection.Capabilities.Trash {
		used["DeletedAt"] = true
	}
	if collection.Capabilities.Versions {
		used["Status"] = true
		used["Revision"] = true
	}

	result := make([]string, len(collection.Fields))
	for index, field := range collection.Fields {
		if !goFieldAppearsInModel(field) {
			continue
		}
		base := exportedGoIdentifier(field.Name)
		name := base
		if used[name] {
			name = base + "Field"
			for suffix := 2; used[name] || natural[name]; suffix++ {
				name = base + "Field" + fmt.Sprint(suffix)
			}
		}
		used[name] = true
		result[index] = name
	}
	return result
}

func goFieldAppearsInModel(field schema.Field) bool {
	return field.Category != schema.FieldCategoryPresentation || field.Type == schema.FieldTypeJoin || field.Type == schema.FieldTypeVirtual
}

func goFieldType(field schema.Field, mode goModelMode, pluginTypes map[string]string) string {
	switch field.Type {
	case schema.FieldTypeText, schema.FieldTypeCode, schema.FieldTypeTextarea, schema.FieldTypeEmail, schema.FieldTypeDate, schema.FieldTypeRadio:
		return "string"
	case schema.FieldTypeSelect:
		if field.Select != nil && field.Select.HasMany {
			return "[]string"
		}
		return "string"
	case schema.FieldTypePoint:
		return "[2]float64"
	case schema.FieldTypeNumber:
		return "float64"
	case schema.FieldTypeCheckbox:
		return "bool"
	case schema.FieldTypeVirtual:
		if field.Virtual == nil {
			return "any"
		}
		switch field.Virtual.ValueType {
		case schema.ValueTypeString:
			return "string"
		case schema.ValueTypeNumber:
			return "float64"
		case schema.ValueTypeBoolean:
			return "bool"
		default:
			return "any"
		}
	case schema.FieldTypeJoin:
		return "[]map[string]any"
	case schema.FieldTypeRelationship:
		if field.Relationship != nil && field.Relationship.HasMany {
			return "[]string"
		}
		if field.Relationship != nil && field.Relationship.Polymorphic {
			return "map[string]any"
		}
		return "string"
	case schema.FieldTypeUpload:
		if field.Upload != nil && field.Upload.HasMany {
			return "[]string"
		}
		return "string"
	case schema.FieldTypeGroup:
		if field.Nested == nil {
			return "map[string]any"
		}
		return goAnonymousStruct(field.Nested.Fields, mode, pluginTypes)
	case schema.FieldTypeArray:
		if field.Nested == nil {
			return "[]map[string]any"
		}
		return "[]" + goAnonymousStruct(field.Nested.Fields, mode, pluginTypes)
	case schema.FieldTypeBlocks:
		return "[]map[string]any"
	case schema.FieldTypePlugin:
		if field.Plugin != nil {
			if typeName, exists := pluginTypes[field.Plugin.Key]; exists {
				return typeName
			}
		}
		return "json.RawMessage"
	default:
		return "any"
	}
}

func goAnonymousStruct(fields []schema.Field, mode goModelMode, pluginTypes map[string]string) string {
	var output strings.Builder
	output.WriteString("struct { ")
	for _, field := range fields {
		if field.Category == schema.FieldCategoryPresentation {
			continue
		}
		fieldType := goFieldType(field, mode, pluginTypes)
		// Nested output fields can be redacted or projected independently too.
		optional := mode == goOutput || mode == goUpdate || !field.Required || mode == goCreate && generatedFieldHasDefault(field)
		fieldType = goPresenceType(field, fieldType, mode, optional)
		tag := field.Name
		if optional {
			tag += ",omitempty"
		}
		fmt.Fprintf(&output, "%s %s `json:%q`; ", exportedGoIdentifier(field.Name), fieldType, tag)
	}
	output.WriteString("}")
	return output.String()
}

func goPresenceType(field schema.Field, fieldType string, mode goModelMode, optional bool) string {
	nullable := !field.Required
	// A plugin-owned named Go type can have a nil-able underlying type or a
	// custom marshaler that emits null. The manifest intentionally does not
	// expose executable type internals, so mutation generation must treat every
	// exact plugin input type as unproven rather than guessing from its name.
	nonNullInput := mode != goOutput && !nullable && (field.Type == schema.FieldTypePlugin || goTypeCanEncodeNull(fieldType))
	if !optional {
		if nonNullInput {
			return "core.NonNullInput[" + fieldType + "]"
		}
		return fieldType
	}
	if mode == goCreate || mode == goUpdate {
		if nullable {
			return "*core.Input[" + fieldType + "]"
		}
		if nonNullInput {
			return "*core.NonNullInput[" + fieldType + "]"
		}
		return "*" + fieldType
	}
	if !strings.HasPrefix(fieldType, "*") && !strings.HasPrefix(fieldType, "[]") && fieldType != "any" {
		return "*" + fieldType
	}
	return fieldType
}

func goTypeCanEncodeNull(fieldType string) bool {
	return fieldType == "any" ||
		fieldType == "json.RawMessage" ||
		strings.HasPrefix(fieldType, "[]") ||
		strings.HasPrefix(fieldType, "map[") ||
		strings.HasPrefix(fieldType, "interface{")
}

func generatedFieldHasDefault(field schema.Field) bool {
	return field.Default != nil ||
		field.Select != nil && field.Select.HasMany && len(field.Select.DefaultValues) != 0 ||
		field.Text != nil && field.Text.Slug != nil
}

func goPluginTypes(snapshot schema.Snapshot) (map[string]string, map[string]string, bool) {
	available := make(map[string]schema.PluginFieldType)
	for _, plugin := range snapshot.Plugins {
		for _, fieldType := range plugin.FieldTypes {
			if fieldType.GoPackage != "" && fieldType.GoType != "" {
				available[fieldType.Key] = fieldType
			}
		}
	}
	used := make(map[string]bool)
	needsJSON := false
	var inspect func([]schema.Field)
	inspect = func(fields []schema.Field) {
		for _, field := range fields {
			if field.Type == schema.FieldTypePlugin {
				if field.Plugin == nil || available[field.Plugin.Key].Key == "" {
					needsJSON = true
				} else {
					used[field.Plugin.Key] = true
				}
			}
			if field.Nested != nil {
				inspect(field.Nested.Fields)
			}
			if field.Blocks != nil {
				for _, block := range field.Blocks.Types {
					inspect(block.Fields)
				}
			}
		}
	}
	for _, collection := range snapshot.Collections {
		inspect(collection.Fields)
	}
	for _, global := range snapshot.Globals {
		inspect(global.Fields)
	}

	result := make(map[string]string)
	imports := make(map[string]string)
	usedAliases := map[string]int{"core": 1, "json": 1}
	for _, plugin := range snapshot.Plugins {
		for _, fieldType := range plugin.FieldTypes {
			if !used[fieldType.Key] || fieldType.GoPackage == "" || fieldType.GoType == "" {
				continue
			}
			alias, exists := imports[fieldType.GoPackage]
			if !exists {
				parts := strings.Split(fieldType.GoPackage, "/")
				base := strings.ToLower(exportedGoIdentifier(parts[len(parts)-1]))
				if base == "" {
					base = "plugin"
				}
				alias = base
				usedAliases[base]++
				if usedAliases[base] > 1 {
					alias += fmt.Sprint(usedAliases[base])
				}
				imports[fieldType.GoPackage] = alias
			}
			result[fieldType.Key] = alias + "." + fieldType.GoType
		}
	}
	return result, imports, needsJSON
}

func exportedGoIdentifier(value string) string {
	var words []string
	var current []rune
	flush := func() {
		if len(current) != 0 {
			words = append(words, string(current))
			current = nil
		}
	}
	for index, character := range []rune(value) {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			flush()
			continue
		}
		if unicode.IsUpper(character) && index > 0 && len(current) != 0 {
			flush()
		}
		current = append(current, character)
	}
	flush()
	for index, word := range words {
		runes := []rune(strings.ToLower(word))
		if len(runes) != 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		words[index] = string(runes)
	}
	result := strings.Join(words, "")
	if result != "" && unicode.IsDigit([]rune(result)[0]) {
		result = "Value" + result
	}
	keywords := []string{"Break", "Default", "Func", "Interface", "Select", "Case", "Defer", "Go", "Map", "Struct", "Chan", "Else", "Goto", "Package", "Switch", "Const", "Fallthrough", "If", "Range", "Type", "Continue", "For", "Import", "Return", "Var"}
	sort.Strings(keywords)
	if index := sort.SearchStrings(keywords, result); index < len(keywords) && keywords[index] == result {
		result += "Value"
	}
	return result
}
