package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/riducms/ridu/schema"
)

func TestGeneratedGoModelsDisambiguateFrameworkMembersAndCompile(t *testing.T) {
	manifest := schema.NewManifest(schema.Snapshot{
		Version: schema.CurrentVersion, Application: schema.Application{Name: "Go field collisions"},
		Collections: []schema.Collection{{
			ID: "articles", Slug: "articles", Labels: schema.CollectionLabels{Singular: "Article", Plural: "Articles"},
			Capabilities: schema.Capabilities{Versions: true, Trash: true},
			Versions:     &schema.VersionSettings{Drafts: true, MaxPerDocument: 10},
			Fields: []schema.Field{
				{ID: "articles-id", Name: "iD", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-created", Name: "created_at", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-updated", Name: "updated_at", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-deleted", Name: "deleted_at", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-status-field", Name: "statusField", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-status", Name: "status", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-revision", Name: "revision", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
				{ID: "articles-title", Name: "title", Type: schema.FieldTypeText, Category: schema.FieldCategoryScalar},
			},
		}},
	})
	generated, err := goClient(manifest)
	if err != nil {
		t.Fatal(err)
	}
	expectedSource := strings.ReplaceAll(`// Code generated by Ridu. DO NOT EDIT.
package generated

import (
	"github.com/riducms/ridu/core"
)

type Article struct {
	ID string §json:"id"§
	CreatedAt string §json:"createdAt"§
	UpdatedAt string §json:"updatedAt"§
	DeletedAt *string §json:"deletedAt,omitempty"§
	Status string §json:"_status"§
	Revision int §json:"_revision"§
	IDField *string §json:"iD,omitempty"§
	CreatedAtField *string §json:"created_at,omitempty"§
	UpdatedAtField *string §json:"updated_at,omitempty"§
	DeletedAtField *string §json:"deleted_at,omitempty"§
	StatusField *string §json:"statusField,omitempty"§
	StatusField2 *string §json:"status,omitempty"§
	RevisionField *string §json:"revision,omitempty"§
	Title *string §json:"title,omitempty"§
}

type ArticleCreate struct {
	IDField *core.Input[string] §json:"iD,omitempty"§
	CreatedAtField *core.Input[string] §json:"created_at,omitempty"§
	UpdatedAtField *core.Input[string] §json:"updated_at,omitempty"§
	DeletedAtField *core.Input[string] §json:"deleted_at,omitempty"§
	StatusField *core.Input[string] §json:"statusField,omitempty"§
	StatusField2 *core.Input[string] §json:"status,omitempty"§
	RevisionField *core.Input[string] §json:"revision,omitempty"§
	Title *core.Input[string] §json:"title,omitempty"§
}

type ArticleUpdate struct {
	IDField *core.Input[string] §json:"iD,omitempty"§
	CreatedAtField *core.Input[string] §json:"created_at,omitempty"§
	UpdatedAtField *core.Input[string] §json:"updated_at,omitempty"§
	DeletedAtField *core.Input[string] §json:"deleted_at,omitempty"§
	StatusField *core.Input[string] §json:"statusField,omitempty"§
	StatusField2 *core.Input[string] §json:"status,omitempty"§
	RevisionField *core.Input[string] §json:"revision,omitempty"§
	Title *core.Input[string] §json:"title,omitempty"§
}

var ArticlesCollection = core.NewTypedCollection[Article, ArticleCreate, ArticleUpdate]("articles")
`, "§", "`")
	expected, err := format.Source([]byte(expectedSource))
	if err != nil {
		t.Fatalf("format expected generated Go: %v", err)
	}
	if !bytes.Equal(generated, expected) {
		t.Fatalf("generated Go collision output differs:\n--- got ---\n%s\n--- want ---\n%s", generated, expected)
	}
	compileGeneratedGo(t, generated)
}

func compileGeneratedGo(t *testing.T, generated []byte) {
	t.Helper()
	frameworkRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	directory := t.TempDir()
	goModule := fmt.Sprintf("module example.com/ridu-generated-collision\n\ngo 1.25.13\n\nrequire github.com/riducms/ridu v0.0.0\n\nreplace github.com/riducms/ridu => %s\n", filepath.ToSlash(frameworkRoot))
	if err := os.WriteFile(filepath.Join(directory, "go.mod"), []byte(goModule), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "ridu.generated.go"), generated, 0o644); err != nil {
		t.Fatal(err)
	}
	command := exec.CommandContext(t.Context(), "go", "test", "-mod=mod", "./...")
	command.Dir = directory
	command.Env = append(os.Environ(), "GOWORK=off")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("compile generated Go collision fixture: %v\n%s\n%s", err, output, generated)
	}
}
